/*
 * Decompiled with CFR 0_125.
 * 
 * Could not load the following classes:
 *  danger.orespawn.ModelTheKing
 *  danger.orespawn.TheKing
 *  net.minecraft.client.model.ModelBase
 *  net.minecraft.client.model.ModelRenderer
 *  net.minecraft.entity.Entity
 *  net.minecraft.util.MathHelper
 *  org.lwjgl.opengl.GL11
 */
package danger.orespawn;

import danger.orespawn.TheKing;
import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;
import net.minecraft.util.MathHelper;
import org.lwjgl.opengl.GL11;

public class ModelTheKing
extends ModelBase {
    private float wingspeed = 1.0f;
    ModelRenderer LCClaw1;
    ModelRenderer LThigh;
    ModelRenderer LUpperLeg;
    ModelRenderer TailTip;
    ModelRenderer Tail1;
    ModelRenderer Tail2;
    ModelRenderer Tail3;
    ModelRenderer Tail4;
    ModelRenderer Tail5;
    ModelRenderer Tail6;
    ModelRenderer Tail7;
    ModelRenderer Body1;
    ModelRenderer Chest;
    ModelRenderer NeckC1;
    ModelRenderer LLowerLeg;
    ModelRenderer LFoot;
    ModelRenderer LLClaw1;
    ModelRenderer LRClaw1;
    ModelRenderer LCClaw2;
    ModelRenderer LLClaw2;
    ModelRenderer TailSpike;
    ModelRenderer LRClaw2;
    ModelRenderer LClawRear;
    ModelRenderer NeckL1;
    ModelRenderer NeckR1;
    ModelRenderer RThigh;
    ModelRenderer RUpperLeg;
    ModelRenderer RLowerLeg;
    ModelRenderer RFoot;
    ModelRenderer RClawRear;
    ModelRenderer RLClaw1;
    ModelRenderer RCClaw1;
    ModelRenderer RRClaw1;
    ModelRenderer RLClaw2;
    ModelRenderer RCClaw2;
    ModelRenderer RRClaw2;
    ModelRenderer NeckL2;
    ModelRenderer NeckC2;
    ModelRenderer NeckR2;
    ModelRenderer NeckL3;
    ModelRenderer NeckC3;
    ModelRenderer NeckR3;
    ModelRenderer NeckL4;
    ModelRenderer LHead1;
    ModelRenderer LHead2;
    ModelRenderer LHead3;
    ModelRenderer LJaw1;
    ModelRenderer LJaw2;
    ModelRenderer LJaw3;
    ModelRenderer LTooth1;
    ModelRenderer LTooth2;
    ModelRenderer LTooth3;
    ModelRenderer LTooth4;
    ModelRenderer NeckC4;
    ModelRenderer NeckR4;
    ModelRenderer CHead1;
    ModelRenderer RHead1;
    ModelRenderer CHead2;
    ModelRenderer RHead2;
    ModelRenderer CHead3;
    ModelRenderer RHead3;
    ModelRenderer CJaw1;
    ModelRenderer CJaw2;
    ModelRenderer CJaw3;
    ModelRenderer RJaw1;
    ModelRenderer RJaw2;
    ModelRenderer RJaw3;
    ModelRenderer CTooth3;
    ModelRenderer CTooth4;
    ModelRenderer CTooth1;
    ModelRenderer CTooth2;
    ModelRenderer RTooth3;
    ModelRenderer RTooth4;
    ModelRenderer RTooth1;
    ModelRenderer RTooth2;
    ModelRenderer LLEye;
    ModelRenderer LREye;
    ModelRenderer CLEye;
    ModelRenderer CREye;
    ModelRenderer RLEye;
    ModelRenderer RREye;
    ModelRenderer LHeadMane;
    ModelRenderer CHeadMane;
    ModelRenderer RHeadMane;
    ModelRenderer LLNoseSpike;
    ModelRenderer LRNoseSpike;
    ModelRenderer CLNoseSpike;
    ModelRenderer CRNoseSpike;
    ModelRenderer RLNoseSpike;
    ModelRenderer RRNoseSpike;
    ModelRenderer Back1;
    ModelRenderer Back2;
    ModelRenderer Lwing1;
    ModelRenderer Lwing2;
    ModelRenderer Lwing3;
    ModelRenderer Lwing4;
    ModelRenderer Lwing5;
    ModelRenderer Lwing6;
    ModelRenderer Lwing7;
    ModelRenderer Lwing9;
    ModelRenderer Lwing8;
    ModelRenderer Lwing10;
    ModelRenderer Rwing1;
    ModelRenderer Rwing2;
    ModelRenderer Rwing3;
    ModelRenderer Rwing4;
    ModelRenderer Rwing5;
    ModelRenderer Rwing6;
    ModelRenderer Rwing7;
    ModelRenderer Rwing8;
    ModelRenderer Rwing9;
    ModelRenderer Rwing10;
    ModelRenderer TailTip2;
    ModelRenderer Ridge1;
    ModelRenderer Ridge2;
    ModelRenderer Ridge3;
    ModelRenderer Ridge4;
    ModelRenderer Ridge5;
    ModelRenderer Ridge6;

    public ModelTheKing(float f1) {
        this.wingspeed = f1;
        this.textureWidth = 2048;
        this.textureHeight = 2048;
        this.LCClaw1 = new ModelRenderer((ModelBase)this, 0, 1450);
        this.LCClaw1.addBox(-5.0f, -5.0f, -20.0f, 10, 10, 20);
        this.LCClaw1.setRotationPoint(52.0f, -2.0f, -7.0f);
        this.LCClaw1.setTextureSize(64, 32);
        this.LCClaw1.mirror = true;
        this.setRotation(this.LCClaw1, 0.3839724f, 0.0f, 0.0f);
        this.LThigh = new ModelRenderer((ModelBase)this, 0, 1050);
        this.LThigh.addBox(0.0f, -14.0f, -21.0f, 25, 34, 42);
        this.LThigh.setRotationPoint(40.0f, -91.0f, 2.0f);
        this.LThigh.setTextureSize(64, 32);
        this.LThigh.mirror = true;
        this.setRotation(this.LThigh, 0.7853982f, 0.0f, 0.0f);
        this.LUpperLeg = new ModelRenderer((ModelBase)this, 0, 1137);
        this.LUpperLeg.addBox(0.0f, 12.0f, -16.0f, 24, 52, 24);
        this.LUpperLeg.setRotationPoint(40.0f, -91.0f, 2.0f);
        this.LUpperLeg.setTextureSize(64, 32);
        this.LUpperLeg.mirror = true;
        this.setRotation(this.LUpperLeg, 0.7853982f, 0.0f, 0.0f);
        this.TailTip = new ModelRenderer((ModelBase)this, 500, 102);
        this.TailTip.addBox(-51.0f, -3.0f, 0.0f, 100, 6, 36);
        this.TailTip.setRotationPoint(0.0f, -86.0f, 308.0f);
        this.TailTip.setTextureSize(64, 32);
        this.TailTip.mirror = true;
        this.setRotation(this.TailTip, 0.0f, 0.0f, 0.0f);
        this.Tail1 = new ModelRenderer((ModelBase)this, 500, 614);
        this.Tail1.addBox(-32.0f, 0.0f, 0.0f, 64, 52, 58);
        this.Tail1.setRotationPoint(0.0f, -114.0f, 29.0f);
        this.Tail1.setTextureSize(64, 32);
        this.Tail1.mirror = true;
        this.setRotation(this.Tail1, 0.0f, 0.0f, 0.0f);
        this.Tail2 = new ModelRenderer((ModelBase)this, 500, 520);
        this.Tail2.addBox(-25.0f, -19.0f, -3.0f, 50, 42, 46);
        this.Tail2.setRotationPoint(0.0f, -90.0f, 79.0f);
        this.Tail2.setTextureSize(64, 32);
        this.Tail2.mirror = true;
        this.setRotation(this.Tail2, 0.0f, 0.0f, 0.0f);
        this.Tail3 = new ModelRenderer((ModelBase)this, 500, 432);
        this.Tail3.addBox(-20.0f, -18.0f, 0.0f, 40, 36, 45);
        this.Tail3.setRotationPoint(0.0f, -88.0f, 117.0f);
        this.Tail3.setTextureSize(64, 32);
        this.Tail3.mirror = true;
        this.setRotation(this.Tail3, 0.0f, 0.0f, 0.0f);
        this.Tail4 = new ModelRenderer((ModelBase)this, 500, 355);
        this.Tail4.addBox(-16.0f, -15.0f, 0.0f, 32, 30, 38);
        this.Tail4.setRotationPoint(0.0f, -87.0f, 156.0f);
        this.Tail4.setTextureSize(64, 32);
        this.Tail4.mirror = true;
        this.setRotation(this.Tail4, 0.0f, 0.0f, 0.0f);
        this.Tail5 = new ModelRenderer((ModelBase)this, 500, 286);
        this.Tail5.addBox(-13.0f, -12.0f, 0.0f, 26, 24, 38);
        this.Tail5.setRotationPoint(0.0f, -87.0f, 189.0f);
        this.Tail5.setTextureSize(64, 32);
        this.Tail5.mirror = true;
        this.setRotation(this.Tail5, 0.0f, 0.0f, 0.0f);
        this.Tail6 = new ModelRenderer((ModelBase)this, 500, 218);
        this.Tail6.addBox(-10.0f, -9.0f, 0.0f, 20, 18, 44);
        this.Tail6.setRotationPoint(0.0f, -87.0f, 222.0f);
        this.Tail6.setTextureSize(64, 32);
        this.Tail6.mirror = true;
        this.setRotation(this.Tail6, 0.0f, 0.0f, 0.0f);
        this.Tail7 = new ModelRenderer((ModelBase)this, 500, 150);
        this.Tail7.addBox(-8.0f, -6.0f, -7.0f, 16, 12, 49);
        this.Tail7.setRotationPoint(0.0f, -87.0f, 268.0f);
        this.Tail7.setTextureSize(64, 32);
        this.Tail7.mirror = true;
        this.setRotation(this.Tail7, 0.0f, 0.0f, 0.0f);
        this.Body1 = new ModelRenderer((ModelBase)this, 500, 732);
        this.Body1.addBox(-40.0f, -32.0f, -36.0f, 80, 64, 72);
        this.Body1.setRotationPoint(0.0f, -89.0f, 1.0f);
        this.Body1.setTextureSize(64, 32);
        this.Body1.mirror = true;
        this.setRotation(this.Body1, 0.0f, 0.0f, 0.0f);
        this.Chest = new ModelRenderer((ModelBase)this, 0, 73);
        this.Chest.addBox(-41.0f, -32.0f, -60.0f, 82, 44, 60);
        this.Chest.setRotationPoint(0.0f, -91.0f, -22.0f);
        this.Chest.setTextureSize(64, 32);
        this.Chest.mirror = true;
        this.setRotation(this.Chest, 0.0f, 0.0f, 0.0f);
        this.NeckC1 = new ModelRenderer((ModelBase)this, 700, 1100);
        this.NeckC1.addBox(-12.0f, -12.0f, -24.0f, 24, 24, 24);
        this.NeckC1.setRotationPoint(0.0f, -113.0f, -76.0f);
        this.NeckC1.setTextureSize(64, 32);
        this.NeckC1.mirror = true;
        this.setRotation(this.NeckC1, -0.1047198f, 0.0f, 0.0f);
        this.LLowerLeg = new ModelRenderer((ModelBase)this, 0, 1220);
        this.LLowerLeg.addBox(-11.0f, 0.0f, -10.0f, 22, 59, 20);
        this.LLowerLeg.setRotationPoint(52.0f, -52.0f, 36.0f);
        this.LLowerLeg.setTextureSize(64, 32);
        this.LLowerLeg.mirror = true;
        this.setRotation(this.LLowerLeg, -0.6283185f, 0.0f, 0.0f);
        this.LFoot = new ModelRenderer((ModelBase)this, 0, 1307);
        this.LFoot.addBox(-18.0f, 59.0f, -10.0f, 36, 12, 20);
        this.LFoot.setRotationPoint(52.0f, -52.0f, 36.0f);
        this.LFoot.setTextureSize(64, 32);
        this.LFoot.mirror = true;
        this.setRotation(this.LFoot, -0.6283185f, 0.0f, 0.0f);
        this.LLClaw1 = new ModelRenderer((ModelBase)this, 0, 1400);
        this.LLClaw1.addBox(-5.0f, -5.0f, -20.0f, 10, 10, 20);
        this.LLClaw1.setRotationPoint(67.0f, -2.0f, -7.0f);
        this.LLClaw1.setTextureSize(64, 32);
        this.LLClaw1.mirror = true;
        this.setRotation(this.LLClaw1, 0.3839724f, 0.0f, 0.0f);
        this.LRClaw1 = new ModelRenderer((ModelBase)this, 0, 1500);
        this.LRClaw1.addBox(-5.0f, -5.0f, -20.0f, 10, 10, 20);
        this.LRClaw1.setRotationPoint(37.0f, -2.0f, -7.0f);
        this.LRClaw1.setTextureSize(64, 32);
        this.LRClaw1.mirror = true;
        this.setRotation(this.LRClaw1, 0.3839724f, 0.0f, 0.0f);
        this.LCClaw2 = new ModelRenderer((ModelBase)this, 0, 1600);
        this.LCClaw2.addBox(-2.0f, -7.0f, -46.0f, 4, 7, 28);
        this.LCClaw2.setRotationPoint(52.0f, -2.0f, -7.0f);
        this.LCClaw2.setTextureSize(64, 32);
        this.LCClaw2.mirror = true;
        this.setRotation(this.LCClaw2, 0.6457718f, 0.0f, 0.0f);
        this.LLClaw2 = new ModelRenderer((ModelBase)this, 0, 1550);
        this.LLClaw2.addBox(-2.0f, -7.0f, -46.0f, 4, 7, 28);
        this.LLClaw2.setRotationPoint(67.0f, -2.0f, -7.0f);
        this.LLClaw2.setTextureSize(64, 32);
        this.LLClaw2.mirror = true;
        this.setRotation(this.LLClaw2, 0.6457718f, 0.0f, 0.0f);
        this.TailSpike = new ModelRenderer((ModelBase)this, 500, 0);
        this.TailSpike.addBox(-2.0f, -1.0f, -7.0f, 4, 4, 53);
        this.TailSpike.setRotationPoint(0.0f, -87.0f, 375.0f);
        this.TailSpike.setTextureSize(64, 32);
        this.TailSpike.mirror = true;
        this.setRotation(this.TailSpike, 0.0f, 0.0f, 0.0f);
        this.LRClaw2 = new ModelRenderer((ModelBase)this, 0, 1650);
        this.LRClaw2.addBox(-2.0f, -7.0f, -46.0f, 4, 7, 28);
        this.LRClaw2.setRotationPoint(37.0f, -2.0f, -7.0f);
        this.LRClaw2.setTextureSize(64, 32);
        this.LRClaw2.mirror = true;
        this.setRotation(this.LRClaw2, 0.6457718f, 0.0f, 0.0f);
        this.LClawRear = new ModelRenderer((ModelBase)this, 0, 1350);
        this.LClawRear.addBox(-2.0f, -3.0f, 0.0f, 4, 9, 28);
        this.LClawRear.setRotationPoint(52.0f, 4.0f, 4.0f);
        this.LClawRear.setTextureSize(64, 32);
        this.LClawRear.mirror = true;
        this.setRotation(this.LClawRear, -0.9250245f, 0.0f, 0.0f);
        this.NeckL1 = new ModelRenderer((ModelBase)this, 500, 1100);
        this.NeckL1.addBox(-12.0f, -12.0f, -24.0f, 24, 24, 24);
        this.NeckL1.setRotationPoint(30.0f, -113.0f, -76.0f);
        this.NeckL1.setTextureSize(64, 32);
        this.NeckL1.mirror = true;
        this.setRotation(this.NeckL1, -0.0523599f, -0.1047198f, 0.0f);
        this.NeckR1 = new ModelRenderer((ModelBase)this, 900, 1100);
        this.NeckR1.addBox(-12.0f, -12.0f, -24.0f, 24, 24, 24);
        this.NeckR1.setRotationPoint(-30.0f, -113.0f, -76.0f);
        this.NeckR1.setTextureSize(64, 32);
        this.NeckR1.mirror = true;
        this.setRotation(this.NeckR1, -0.0523599f, 0.1047198f, 0.0f);
        this.RThigh = new ModelRenderer((ModelBase)this, 200, 1050);
        this.RThigh.addBox(0.0f, -14.0f, -21.0f, 25, 34, 42);
        this.RThigh.setRotationPoint(-65.0f, -91.0f, 2.0f);
        this.RThigh.setTextureSize(64, 32);
        this.RThigh.mirror = true;
        this.setRotation(this.RThigh, 0.7853982f, 0.0f, 0.0f);
        this.RUpperLeg = new ModelRenderer((ModelBase)this, 200, 1137);
        this.RUpperLeg.addBox(0.0f, 12.0f, -16.0f, 24, 52, 24);
        this.RUpperLeg.setRotationPoint(-64.0f, -91.0f, 2.0f);
        this.RUpperLeg.setTextureSize(64, 32);
        this.RUpperLeg.mirror = true;
        this.setRotation(this.RUpperLeg, 0.7853982f, 0.0f, 0.0f);
        this.RLowerLeg = new ModelRenderer((ModelBase)this, 200, 1220);
        this.RLowerLeg.addBox(-4.0f, 0.0f, -10.0f, 22, 59, 20);
        this.RLowerLeg.setRotationPoint(-59.0f, -52.0f, 36.0f);
        this.RLowerLeg.setTextureSize(64, 32);
        this.RLowerLeg.mirror = true;
        this.setRotation(this.RLowerLeg, -0.6283185f, 0.0f, 0.0f);
        this.RFoot = new ModelRenderer((ModelBase)this, 200, 1307);
        this.RFoot.addBox(-11.0f, 59.0f, -10.0f, 36, 12, 20);
        this.RFoot.setRotationPoint(-59.0f, -52.0f, 36.0f);
        this.RFoot.setTextureSize(64, 32);
        this.RFoot.mirror = true;
        this.setRotation(this.RFoot, -0.6283185f, 0.0f, 0.0f);
        this.RClawRear = new ModelRenderer((ModelBase)this, 200, 1350);
        this.RClawRear.addBox(-2.0f, -3.0f, 0.0f, 4, 9, 28);
        this.RClawRear.setRotationPoint(-52.0f, 4.0f, 4.0f);
        this.RClawRear.setTextureSize(64, 32);
        this.RClawRear.mirror = true;
        this.setRotation(this.RClawRear, -0.9250245f, 0.0f, 0.0f);
        this.RLClaw1 = new ModelRenderer((ModelBase)this, 200, 1400);
        this.RLClaw1.addBox(-5.0f, -5.0f, -20.0f, 10, 10, 20);
        this.RLClaw1.setRotationPoint(-37.0f, -2.0f, -7.0f);
        this.RLClaw1.setTextureSize(64, 32);
        this.RLClaw1.mirror = true;
        this.setRotation(this.RLClaw1, 0.3839724f, 0.0f, 0.0f);
        this.RCClaw1 = new ModelRenderer((ModelBase)this, 200, 1450);
        this.RCClaw1.addBox(-5.0f, -5.0f, -20.0f, 10, 10, 20);
        this.RCClaw1.setRotationPoint(-52.0f, -2.0f, -7.0f);
        this.RCClaw1.setTextureSize(64, 32);
        this.RCClaw1.mirror = true;
        this.setRotation(this.RCClaw1, 0.3839724f, 0.0f, 0.0f);
        this.RRClaw1 = new ModelRenderer((ModelBase)this, 200, 1500);
        this.RRClaw1.addBox(-5.0f, -5.0f, -20.0f, 10, 10, 20);
        this.RRClaw1.setRotationPoint(-67.0f, -2.0f, -7.0f);
        this.RRClaw1.setTextureSize(64, 32);
        this.RRClaw1.mirror = true;
        this.setRotation(this.RRClaw1, 0.3839724f, 0.0f, 0.0f);
        this.RLClaw2 = new ModelRenderer((ModelBase)this, 200, 1550);
        this.RLClaw2.addBox(-2.0f, -7.0f, -46.0f, 4, 7, 28);
        this.RLClaw2.setRotationPoint(-37.0f, -2.0f, -7.0f);
        this.RLClaw2.setTextureSize(64, 32);
        this.RLClaw2.mirror = true;
        this.setRotation(this.RLClaw2, 0.6457718f, 0.0f, 0.0f);
        this.RCClaw2 = new ModelRenderer((ModelBase)this, 200, 1600);
        this.RCClaw2.addBox(-2.0f, -7.0f, -46.0f, 4, 7, 28);
        this.RCClaw2.setRotationPoint(-52.0f, -2.0f, -7.0f);
        this.RCClaw2.setTextureSize(64, 32);
        this.RCClaw2.mirror = true;
        this.setRotation(this.RCClaw2, 0.6457718f, 0.0f, 0.0f);
        this.RRClaw2 = new ModelRenderer((ModelBase)this, 200, 1650);
        this.RRClaw2.addBox(-2.0f, -7.0f, -46.0f, 4, 7, 28);
        this.RRClaw2.setRotationPoint(-67.0f, -2.0f, -7.0f);
        this.RRClaw2.setTextureSize(64, 32);
        this.RRClaw2.mirror = true;
        this.setRotation(this.RRClaw2, 0.6457718f, 0.0f, 0.0f);
        this.NeckL2 = new ModelRenderer((ModelBase)this, 500, 1154);
        this.NeckL2.addBox(-11.0f, -11.0f, -40.0f, 22, 22, 40);
        this.NeckL2.setRotationPoint(32.0f, -114.0f, -95.0f);
        this.NeckL2.setTextureSize(64, 32);
        this.NeckL2.mirror = true;
        this.setRotation(this.NeckL2, 0.0f, -0.1745329f, 0.0f);
        this.NeckC2 = new ModelRenderer((ModelBase)this, 700, 1154);
        this.NeckC2.addBox(-11.0f, -11.0f, -40.0f, 22, 22, 40);
        this.NeckC2.setRotationPoint(0.0f, -115.0f, -95.0f);
        this.NeckC2.setTextureSize(64, 32);
        this.NeckC2.mirror = true;
        this.setRotation(this.NeckC2, -0.1570796f, 0.0f, 0.0f);
        this.NeckR2 = new ModelRenderer((ModelBase)this, 900, 1154);
        this.NeckR2.addBox(-11.0f, -11.0f, -40.0f, 22, 22, 40);
        this.NeckR2.setRotationPoint(-32.0f, -114.0f, -95.0f);
        this.NeckR2.setTextureSize(64, 32);
        this.NeckR2.mirror = true;
        this.setRotation(this.NeckR2, -0.0523599f, 0.1745329f, 0.0f);
        this.NeckL3 = new ModelRenderer((ModelBase)this, 500, 1222);
        this.NeckL3.addBox(-10.0f, -10.0f, -40.0f, 20, 20, 40);
        this.NeckL3.setRotationPoint(38.0f, -114.0f, -131.0f);
        this.NeckL3.setTextureSize(64, 32);
        this.NeckL3.mirror = true;
        this.setRotation(this.NeckL3, 0.0698132f, -0.2617994f, 0.0f);
        this.NeckC3 = new ModelRenderer((ModelBase)this, 700, 1222);
        this.NeckC3.addBox(-10.0f, -10.0f, -40.0f, 20, 20, 40);
        this.NeckC3.setRotationPoint(0.0f, -120.0f, -131.0f);
        this.NeckC3.setTextureSize(64, 32);
        this.NeckC3.mirror = true;
        this.setRotation(this.NeckC3, -0.2094395f, 0.0f, 0.0f);
        this.NeckR3 = new ModelRenderer((ModelBase)this, 900, 1222);
        this.NeckR3.addBox(-10.0f, -10.0f, -40.0f, 20, 20, 40);
        this.NeckR3.setRotationPoint(-37.0f, -116.0f, -128.0f);
        this.NeckR3.setTextureSize(64, 32);
        this.NeckR3.mirror = true;
        this.setRotation(this.NeckR3, -0.0523599f, 0.3141593f, 0.0f);
        this.NeckL4 = new ModelRenderer((ModelBase)this, 500, 1300);
        this.NeckL4.addBox(-9.0f, -9.0f, -40.0f, 18, 18, 40);
        this.NeckL4.setRotationPoint(46.0f, -112.0f, -163.0f);
        this.NeckL4.setTextureSize(64, 32);
        this.NeckL4.mirror = true;
        this.setRotation(this.NeckL4, 0.1396263f, -0.3839724f, 0.0f);
        this.LHead1 = new ModelRenderer((ModelBase)this, 500, 1425);
        this.LHead1.addBox(-13.0f, -13.0f, -30.0f, 26, 26, 30);
        this.LHead1.setRotationPoint(59.0f, -114.0f, -195.0f);
        this.LHead1.setTextureSize(64, 32);
        this.LHead1.mirror = true;
        this.setRotation(this.LHead1, 0.1396263f, -0.3839724f, 0.0f);
        this.LHead2 = new ModelRenderer((ModelBase)this, 500, 1550);
        this.LHead2.addBox(-10.0f, -7.0f, -58.0f, 20, 20, 28);
        this.LHead2.setRotationPoint(59.0f, -114.0f, -195.0f);
        this.LHead2.setTextureSize(64, 32);
        this.LHead2.mirror = true;
        this.setRotation(this.LHead2, 0.1396263f, -0.3839724f, 0.0f);
        this.LHead3 = new ModelRenderer((ModelBase)this, 500, 1605);
        this.LHead3.addBox(-8.0f, -3.0f, -83.0f, 16, 16, 26);
        this.LHead3.setRotationPoint(59.0f, -114.0f, -195.0f);
        this.LHead3.setTextureSize(64, 32);
        this.LHead3.mirror = true;
        this.setRotation(this.LHead3, 0.1396263f, -0.3839724f, 0.0f);
        this.LJaw1 = new ModelRenderer((ModelBase)this, 500, 1660);
        this.LJaw1.addBox(-14.0f, -2.0f, -14.0f, 28, 7, 16);
        this.LJaw1.setRotationPoint(59.0f, -100.0f, -196.0f);
        this.LJaw1.setTextureSize(64, 32);
        this.LJaw1.mirror = true;
        this.setRotation(this.LJaw1, 0.2443461f, -0.3839724f, 0.0f);
        this.LJaw2 = new ModelRenderer((ModelBase)this, 500, 1700);
        this.LJaw2.addBox(-12.0f, -2.0f, -55.0f, 24, 6, 46);
        this.LJaw2.setRotationPoint(59.0f, -100.0f, -196.0f);
        this.LJaw2.setTextureSize(64, 32);
        this.LJaw2.mirror = true;
        this.setRotation(this.LJaw2, 0.2443461f, -0.3839724f, 0.0f);
        this.LJaw3 = new ModelRenderer((ModelBase)this, 500, 1765);
        this.LJaw3.addBox(-10.0f, -2.0f, -77.0f, 20, 6, 22);
        this.LJaw3.setRotationPoint(59.0f, -100.0f, -196.0f);
        this.LJaw3.setTextureSize(64, 32);
        this.LJaw3.mirror = true;
        this.setRotation(this.LJaw3, 0.2443461f, -0.3839724f, 0.0f);
        this.LTooth1 = new ModelRenderer((ModelBase)this, 10, 0);
        this.LTooth1.addBox(-10.0f, -10.0f, -77.0f, 2, 8, 2);
        this.LTooth1.setRotationPoint(59.0f, -100.0f, -196.0f);
        this.LTooth1.setTextureSize(64, 32);
        this.LTooth1.mirror = true;
        this.setRotation(this.LTooth1, 0.2443461f, -0.3839724f, 0.0f);
        this.LTooth2 = new ModelRenderer((ModelBase)this, 20, 0);
        this.LTooth2.addBox(8.0f, -10.0f, -77.0f, 2, 8, 2);
        this.LTooth2.setRotationPoint(59.0f, -100.0f, -196.0f);
        this.LTooth2.setTextureSize(64, 32);
        this.LTooth2.mirror = true;
        this.setRotation(this.LTooth2, 0.2443461f, -0.3839724f, 0.0f);
        this.LTooth3 = new ModelRenderer((ModelBase)this, 30, 0);
        this.LTooth3.addBox(-12.0f, -8.0f, -55.0f, 2, 6, 2);
        this.LTooth3.setRotationPoint(59.0f, -100.0f, -196.0f);
        this.LTooth3.setTextureSize(64, 32);
        this.LTooth3.mirror = true;
        this.setRotation(this.LTooth3, 0.2443461f, -0.3839724f, 0.0f);
        this.LTooth4 = new ModelRenderer((ModelBase)this, 40, 0);
        this.LTooth4.addBox(10.0f, -8.0f, -55.0f, 2, 6, 2);
        this.LTooth4.setRotationPoint(59.0f, -100.0f, -196.0f);
        this.LTooth4.setTextureSize(64, 32);
        this.LTooth4.mirror = true;
        this.setRotation(this.LTooth4, 0.2443461f, -0.3839724f, 0.0f);
        this.NeckC4 = new ModelRenderer((ModelBase)this, 700, 1300);
        this.NeckC4.addBox(-9.0f, -9.0f, -40.0f, 18, 18, 40);
        this.NeckC4.setRotationPoint(0.0f, -126.0f, -162.0f);
        this.NeckC4.setTextureSize(64, 32);
        this.NeckC4.mirror = true;
        this.setRotation(this.NeckC4, -0.2617994f, 0.0f, 0.0f);
        this.NeckR4 = new ModelRenderer((ModelBase)this, 900, 1300);
        this.NeckR4.addBox(-9.0f, -9.0f, -40.0f, 18, 18, 40);
        this.NeckR4.setRotationPoint(-47.0f, -118.0f, -161.0f);
        this.NeckR4.setTextureSize(64, 32);
        this.NeckR4.mirror = true;
        this.setRotation(this.NeckR4, -0.1047198f, 0.3665191f, 0.0f);
        this.CHead1 = new ModelRenderer((ModelBase)this, 700, 1425);
        this.CHead1.addBox(-13.0f, -13.0f, -30.0f, 26, 26, 30);
        this.CHead1.setRotationPoint(0.0f, -141.0f, -195.0f);
        this.CHead1.setTextureSize(64, 32);
        this.CHead1.mirror = true;
        this.setRotation(this.CHead1, -0.296706f, 0.0f, 0.0f);
        this.RHead1 = new ModelRenderer((ModelBase)this, 900, 1425);
        this.RHead1.addBox(-13.0f, -13.0f, -30.0f, 26, 26, 30);
        this.RHead1.setRotationPoint(-60.0f, -128.0f, -195.0f);
        this.RHead1.setTextureSize(64, 32);
        this.RHead1.mirror = true;
        this.setRotation(this.RHead1, -0.122173f, 0.418879f, 0.0f);
        this.CHead2 = new ModelRenderer((ModelBase)this, 700, 1550);
        this.CHead2.addBox(-10.0f, -7.0f, -58.0f, 20, 20, 28);
        this.CHead2.setRotationPoint(0.0f, -141.0f, -195.0f);
        this.CHead2.setTextureSize(64, 32);
        this.CHead2.mirror = true;
        this.setRotation(this.CHead2, -0.296706f, 0.0f, 0.0f);
        this.RHead2 = new ModelRenderer((ModelBase)this, 900, 1550);
        this.RHead2.addBox(-10.0f, -7.0f, -58.0f, 20, 20, 28);
        this.RHead2.setRotationPoint(-60.0f, -128.0f, -195.0f);
        this.RHead2.setTextureSize(64, 32);
        this.RHead2.mirror = true;
        this.setRotation(this.RHead2, -0.122173f, 0.418879f, 0.0f);
        this.CHead3 = new ModelRenderer((ModelBase)this, 700, 1605);
        this.CHead3.addBox(-8.0f, -3.0f, -83.0f, 16, 16, 26);
        this.CHead3.setRotationPoint(0.0f, -141.0f, -195.0f);
        this.CHead3.setTextureSize(64, 32);
        this.CHead3.mirror = true;
        this.setRotation(this.CHead3, -0.296706f, 0.0f, 0.0f);
        this.RHead3 = new ModelRenderer((ModelBase)this, 900, 1605);
        this.RHead3.addBox(-8.0f, -3.0f, -83.0f, 16, 16, 26);
        this.RHead3.setRotationPoint(-60.0f, -128.0f, -195.0f);
        this.RHead3.setTextureSize(64, 32);
        this.RHead3.mirror = true;
        this.setRotation(this.RHead3, -0.122173f, 0.418879f, 0.0f);
        this.CJaw1 = new ModelRenderer((ModelBase)this, 700, 1660);
        this.CJaw1.addBox(-14.0f, -2.0f, -14.0f, 28, 7, 16);
        this.CJaw1.setRotationPoint(0.0f, -130.0f, -201.0f);
        this.CJaw1.setTextureSize(64, 32);
        this.CJaw1.mirror = true;
        this.setRotation(this.CJaw1, -0.1047198f, 0.0f, 0.0f);
        this.CJaw2 = new ModelRenderer((ModelBase)this, 700, 1700);
        this.CJaw2.addBox(-12.0f, -2.0f, -55.0f, 24, 6, 46);
        this.CJaw2.setRotationPoint(0.0f, -130.0f, -201.0f);
        this.CJaw2.setTextureSize(64, 32);
        this.CJaw2.mirror = true;
        this.setRotation(this.CJaw2, -0.1047198f, 0.0f, 0.0f);
        this.CJaw3 = new ModelRenderer((ModelBase)this, 700, 1765);
        this.CJaw3.addBox(-10.0f, -2.0f, -77.0f, 20, 6, 22);
        this.CJaw3.setRotationPoint(0.0f, -130.0f, -201.0f);
        this.CJaw3.setTextureSize(64, 32);
        this.CJaw3.mirror = true;
        this.setRotation(this.CJaw3, -0.1047198f, 0.0f, 0.0f);
        this.RJaw1 = new ModelRenderer((ModelBase)this, 900, 1660);
        this.RJaw1.addBox(-14.0f, -2.0f, -14.0f, 28, 7, 16);
        this.RJaw1.setRotationPoint(-62.0f, -115.0f, -200.0f);
        this.RJaw1.setTextureSize(64, 32);
        this.RJaw1.mirror = true;
        this.setRotation(this.RJaw1, 0.1570796f, 0.418879f, 0.0f);
        this.RJaw2 = new ModelRenderer((ModelBase)this, 900, 1700);
        this.RJaw2.addBox(-12.0f, -2.0f, -55.0f, 24, 6, 46);
        this.RJaw2.setRotationPoint(-62.0f, -115.0f, -200.0f);
        this.RJaw2.setTextureSize(64, 32);
        this.RJaw2.mirror = true;
        this.setRotation(this.RJaw2, 0.1570796f, 0.418879f, 0.0f);
        this.RJaw3 = new ModelRenderer((ModelBase)this, 900, 1765);
        this.RJaw3.addBox(-10.0f, -2.0f, -77.0f, 20, 6, 22);
        this.RJaw3.setRotationPoint(-62.0f, -115.0f, -200.0f);
        this.RJaw3.setTextureSize(64, 32);
        this.RJaw3.mirror = true;
        this.setRotation(this.RJaw3, 0.1570796f, 0.418879f, 0.0f);
        this.CTooth3 = new ModelRenderer((ModelBase)this, 70, 0);
        this.CTooth3.addBox(-12.0f, -8.0f, -55.0f, 2, 6, 2);
        this.CTooth3.setRotationPoint(0.0f, -130.0f, -201.0f);
        this.CTooth3.setTextureSize(64, 32);
        this.CTooth3.mirror = true;
        this.setRotation(this.CTooth3, -0.1047198f, 0.0f, 0.0f);
        this.CTooth4 = new ModelRenderer((ModelBase)this, 80, 0);
        this.CTooth4.addBox(10.0f, -8.0f, -55.0f, 2, 6, 2);
        this.CTooth4.setRotationPoint(0.0f, -130.0f, -201.0f);
        this.CTooth4.setTextureSize(64, 32);
        this.CTooth4.mirror = true;
        this.setRotation(this.CTooth4, -0.1047198f, 0.0f, 0.0f);
        this.CTooth1 = new ModelRenderer((ModelBase)this, 50, 0);
        this.CTooth1.addBox(-10.0f, -10.0f, -77.0f, 2, 8, 2);
        this.CTooth1.setRotationPoint(0.0f, -130.0f, -201.0f);
        this.CTooth1.setTextureSize(64, 32);
        this.CTooth1.mirror = true;
        this.setRotation(this.CTooth1, -0.1047198f, 0.0f, 0.0f);
        this.CTooth2 = new ModelRenderer((ModelBase)this, 60, 0);
        this.CTooth2.addBox(8.0f, -10.0f, -77.0f, 2, 8, 2);
        this.CTooth2.setRotationPoint(0.0f, -130.0f, -201.0f);
        this.CTooth2.setTextureSize(64, 32);
        this.CTooth2.mirror = true;
        this.setRotation(this.CTooth2, -0.1047198f, 0.0f, 0.0f);
        this.RTooth3 = new ModelRenderer((ModelBase)this, 110, 0);
        this.RTooth3.addBox(-12.0f, -8.0f, -55.0f, 2, 6, 2);
        this.RTooth3.setRotationPoint(-62.0f, -115.0f, -200.0f);
        this.RTooth3.setTextureSize(64, 32);
        this.RTooth3.mirror = true;
        this.setRotation(this.RTooth3, 0.1570796f, 0.418879f, 0.0f);
        this.RTooth4 = new ModelRenderer((ModelBase)this, 120, 0);
        this.RTooth4.addBox(10.0f, -8.0f, -55.0f, 2, 6, 2);
        this.RTooth4.setRotationPoint(-62.0f, -115.0f, -200.0f);
        this.RTooth4.setTextureSize(64, 32);
        this.RTooth4.mirror = true;
        this.setRotation(this.RTooth4, 0.1570796f, 0.418879f, 0.0f);
        this.RTooth1 = new ModelRenderer((ModelBase)this, 90, 0);
        this.RTooth1.addBox(-10.0f, -10.0f, -77.0f, 2, 8, 2);
        this.RTooth1.setRotationPoint(-62.0f, -115.0f, -200.0f);
        this.RTooth1.setTextureSize(64, 32);
        this.RTooth1.mirror = true;
        this.setRotation(this.RTooth1, 0.1570796f, 0.418879f, 0.0f);
        this.RTooth2 = new ModelRenderer((ModelBase)this, 100, 0);
        this.RTooth2.addBox(8.0f, -10.0f, -77.0f, 2, 8, 2);
        this.RTooth2.setRotationPoint(-62.0f, -115.0f, -200.0f);
        this.RTooth2.setTextureSize(64, 32);
        this.RTooth2.mirror = true;
        this.setRotation(this.RTooth2, 0.1570796f, 0.418879f, 0.0f);
        this.LLEye = new ModelRenderer((ModelBase)this, 500, 1500);
        this.LLEye.addBox(13.0f, -12.0f, -29.0f, 2, 6, 10);
        this.LLEye.setRotationPoint(59.0f, -114.0f, -195.0f);
        this.LLEye.setTextureSize(64, 32);
        this.LLEye.mirror = true;
        this.setRotation(this.LLEye, 0.1396263f, -0.3839724f, 0.0f);
        this.LREye = new ModelRenderer((ModelBase)this, 533, 1500);
        this.LREye.addBox(-15.0f, -12.0f, -29.0f, 2, 6, 10);
        this.LREye.setRotationPoint(59.0f, -114.0f, -195.0f);
        this.LREye.setTextureSize(64, 32);
        this.LREye.mirror = true;
        this.setRotation(this.LREye, 0.1396263f, -0.3839724f, 0.0f);
        this.CLEye = new ModelRenderer((ModelBase)this, 700, 1500);
        this.CLEye.addBox(13.0f, -12.0f, -29.0f, 2, 6, 10);
        this.CLEye.setRotationPoint(0.0f, -141.0f, -195.0f);
        this.CLEye.setTextureSize(64, 32);
        this.CLEye.mirror = true;
        this.setRotation(this.CLEye, -0.296706f, 0.0f, 0.0f);
        this.CREye = new ModelRenderer((ModelBase)this, 733, 1500);
        this.CREye.addBox(-15.0f, -12.0f, -29.0f, 2, 6, 10);
        this.CREye.setRotationPoint(0.0f, -141.0f, -195.0f);
        this.CREye.setTextureSize(64, 32);
        this.CREye.mirror = true;
        this.setRotation(this.CREye, -0.296706f, 0.0f, 0.0f);
        this.RLEye = new ModelRenderer((ModelBase)this, 900, 1500);
        this.RLEye.addBox(13.0f, -12.0f, -29.0f, 2, 6, 10);
        this.RLEye.setRotationPoint(-60.0f, -128.0f, -195.0f);
        this.RLEye.setTextureSize(64, 32);
        this.RLEye.mirror = true;
        this.setRotation(this.RLEye, -0.122173f, 0.418879f, 0.0f);
        this.RREye = new ModelRenderer((ModelBase)this, 933, 1500);
        this.RREye.addBox(-15.0f, -12.0f, -29.0f, 2, 5, 10);
        this.RREye.setRotationPoint(-60.0f, -128.0f, -195.0f);
        this.RREye.setTextureSize(64, 32);
        this.RREye.mirror = true;
        this.setRotation(this.RREye, -0.122173f, 0.418879f, 0.0f);
        this.LHeadMane = new ModelRenderer((ModelBase)this, 500, 1375);
        this.LHeadMane.addBox(0.0f, -14.0f, 0.0f, 1, 23, 19);
        this.LHeadMane.setRotationPoint(59.0f, -114.0f, -195.0f);
        this.LHeadMane.setTextureSize(64, 32);
        this.LHeadMane.mirror = true;
        this.setRotation(this.LHeadMane, 0.5235988f, -0.3839724f, 0.0f);
        this.CHeadMane = new ModelRenderer((ModelBase)this, 700, 1375);
        this.CHeadMane.addBox(0.0f, -14.0f, 0.0f, 1, 23, 19);
        this.CHeadMane.setRotationPoint(0.0f, -141.0f, -195.0f);
        this.CHeadMane.setTextureSize(64, 32);
        this.CHeadMane.mirror = true;
        this.setRotation(this.CHeadMane, 0.1047198f, 0.0f, 0.0f);
        this.RHeadMane = new ModelRenderer((ModelBase)this, 900, 1375);
        this.RHeadMane.addBox(0.0f, -14.0f, 0.0f, 1, 23, 19);
        this.RHeadMane.setRotationPoint(-60.0f, -128.0f, -195.0f);
        this.RHeadMane.setTextureSize(64, 32);
        this.RHeadMane.mirror = true;
        this.setRotation(this.RHeadMane, 0.3665191f, 0.418879f, 0.0f);
        this.LLNoseSpike = new ModelRenderer((ModelBase)this, 0, 300);
        this.LLNoseSpike.addBox(24.0f, -23.0f, -76.0f, 1, 1, 17);
        this.LLNoseSpike.setRotationPoint(59.0f, -114.0f, -195.0f);
        this.LLNoseSpike.setTextureSize(64, 32);
        this.LLNoseSpike.mirror = true;
        this.setRotation(this.LLNoseSpike, 0.4014257f, -0.1570796f, 0.0f);
        this.LRNoseSpike = new ModelRenderer((ModelBase)this, 0, 325);
        this.LRNoseSpike.addBox(-26.0f, -24.0f, -75.0f, 1, 1, 17);
        this.LRNoseSpike.setRotationPoint(59.0f, -114.0f, -195.0f);
        this.LRNoseSpike.setTextureSize(64, 32);
        this.LRNoseSpike.mirror = true;
        this.setRotation(this.LRNoseSpike, 0.418879f, -0.6283185f, 0.0f);
        this.CLNoseSpike = new ModelRenderer((ModelBase)this, 0, 350);
        this.CLNoseSpike.addBox(24.0f, -23.0f, -76.0f, 1, 1, 17);
        this.CLNoseSpike.setRotationPoint(0.0f, -141.0f, -195.0f);
        this.CLNoseSpike.setTextureSize(64, 32);
        this.CLNoseSpike.mirror = true;
        this.setRotation(this.CLNoseSpike, -0.0523599f, 0.2443461f, 0.0f);
        this.CRNoseSpike = new ModelRenderer((ModelBase)this, 0, 375);
        this.CRNoseSpike.addBox(-26.0f, -24.0f, -75.0f, 1, 1, 17);
        this.CRNoseSpike.setRotationPoint(0.0f, -141.0f, -195.0f);
        this.CRNoseSpike.setTextureSize(64, 32);
        this.CRNoseSpike.mirror = true;
        this.setRotation(this.CRNoseSpike, -0.0349066f, -0.2617994f, 0.0f);
        this.RLNoseSpike = new ModelRenderer((ModelBase)this, 0, 400);
        this.RLNoseSpike.addBox(24.0f, -23.0f, -76.0f, 1, 1, 17);
        this.RLNoseSpike.setRotationPoint(-60.0f, -128.0f, -195.0f);
        this.RLNoseSpike.setTextureSize(64, 32);
        this.RLNoseSpike.mirror = true;
        this.setRotation(this.RLNoseSpike, 0.1396263f, 0.6457718f, 0.0f);
        this.RRNoseSpike = new ModelRenderer((ModelBase)this, 0, 425);
        this.RRNoseSpike.addBox(-26.0f, -24.0f, -75.0f, 1, 1, 17);
        this.RRNoseSpike.setRotationPoint(-60.0f, -128.0f, -195.0f);
        this.RRNoseSpike.setTextureSize(64, 32);
        this.RRNoseSpike.mirror = true;
        this.setRotation(this.RRNoseSpike, 0.1570796f, 0.1745329f, 0.0f);
        this.Back1 = new ModelRenderer((ModelBase)this, 167, 186);
        this.Back1.addBox(0.0f, 0.0f, 0.0f, 30, 15, 49);
        this.Back1.setRotationPoint(-45.0f, -127.0f, -58.0f);
        this.Back1.setTextureSize(64, 32);
        this.Back1.mirror = true;
        this.setRotation(this.Back1, -0.0698132f, 0.0f, 0.0f);
        this.Back2 = new ModelRenderer((ModelBase)this, 0, 186);
        this.Back2.addBox(0.0f, 0.0f, 0.0f, 30, 15, 49);
        this.Back2.setRotationPoint(15.0f, -127.0f, -58.0f);
        this.Back2.setTextureSize(64, 32);
        this.Back2.mirror = true;
        this.setRotation(this.Back2, -0.0698132f, 0.0f, 0.0f);
        this.Lwing1 = new ModelRenderer((ModelBase)this, 250, 1000);
        this.Lwing1.addBox(0.0f, 0.0f, 0.0f, 87, 5, 5);
        this.Lwing1.setRotationPoint(40.0f, -121.0f, -50.0f);
        this.Lwing1.setTextureSize(64, 32);
        this.Lwing1.mirror = true;
        this.setRotation(this.Lwing1, 0.0f, 0.0349066f, 0.0f);
        this.Lwing2 = new ModelRenderer((ModelBase)this, 1220, 782);
        this.Lwing2.addBox(0.0f, 2.0f, 0.0f, 87, 1, 110);
        this.Lwing2.setRotationPoint(40.0f, -121.0f, -49.0f);
        this.Lwing2.setTextureSize(64, 32);
        this.Lwing2.mirror = true;
        this.setRotation(this.Lwing2, 0.0f, 0.0349066f, 0.0f);
        this.Lwing3 = new ModelRenderer((ModelBase)this, 250, 975);
        this.Lwing3.addBox(0.0f, 0.0f, 0.0f, 188, 5, 5);
        this.Lwing3.setRotationPoint(124.0f, -121.0f, -53.0f);
        this.Lwing3.setTextureSize(64, 32);
        this.Lwing3.mirror = true;
        this.setRotation(this.Lwing3, 0.0f, 0.0f, 0.0f);
        this.Lwing4 = new ModelRenderer((ModelBase)this, 1341, 625);
        this.Lwing4.addBox(0.0f, 2.0f, 0.0f, 188, 1, 147);
        this.Lwing4.setRotationPoint(124.0f, -121.0f, -50.0f);
        this.Lwing4.setTextureSize(64, 32);
        this.Lwing4.mirror = true;
        this.setRotation(this.Lwing4, 0.0f, 0.0f, 0.0f);
        this.Lwing5 = new ModelRenderer((ModelBase)this, 245, 950);
        this.Lwing5.addBox(0.0f, 0.0f, 0.0f, 87, 5, 5);
        this.Lwing5.setRotationPoint(309.0f, -121.0f, -53.0f);
        this.Lwing5.setTextureSize(64, 32);
        this.Lwing5.mirror = true;
        this.setRotation(this.Lwing5, 0.0f, -0.0349066f, 0.0f);
        this.Lwing6 = new ModelRenderer((ModelBase)this, 1300, 1300);
        this.Lwing6.addBox(0.0f, 2.0f, 1.0f, 87, 1, 125);
        this.Lwing6.setRotationPoint(309.0f, -121.0f, -50.0f);
        this.Lwing6.setTextureSize(64, 32);
        this.Lwing6.mirror = true;
        this.setRotation(this.Lwing6, 0.0f, 0.0f, 0.0f);
        this.Lwing7 = new ModelRenderer((ModelBase)this, 250, 900);
        this.Lwing7.addBox(0.0f, 0.0f, 0.0f, 150, 5, 5);
        this.Lwing7.setRotationPoint(124.0f, -121.0f, -53.0f);
        this.Lwing7.setTextureSize(64, 32);
        this.Lwing7.mirror = true;
        this.setRotation(this.Lwing7, 0.0f, 0.0f, 0.2617994f);
        this.Lwing9 = new ModelRenderer((ModelBase)this, 250, 925);
        this.Lwing9.addBox(0.0f, 0.0f, 0.0f, 175, 5, 5);
        this.Lwing9.setRotationPoint(124.0f, -121.0f, -53.0f);
        this.Lwing9.setTextureSize(64, 32);
        this.Lwing9.mirror = true;
        this.setRotation(this.Lwing9, 0.0f, 0.0f, -0.2617994f);
        this.Lwing8 = new ModelRenderer((ModelBase)this, 1300, 1156);
        this.Lwing8.addBox(0.0f, 2.0f, 0.0f, 150, 1, 120);
        this.Lwing8.setRotationPoint(124.0f, -121.0f, -50.0f);
        this.Lwing8.setTextureSize(64, 32);
        this.Lwing8.mirror = true;
        this.setRotation(this.Lwing8, 0.0f, 0.0f, 0.2617994f);
        this.Lwing10 = new ModelRenderer((ModelBase)this, 1392, 326);
        this.Lwing10.addBox(0.0f, 2.0f, 0.0f, 176, 1, 136);
        this.Lwing10.setRotationPoint(124.0f, -121.0f, -50.0f);
        this.Lwing10.setTextureSize(64, 32);
        this.Lwing10.mirror = true;
        this.setRotation(this.Lwing10, 0.0f, 0.0f, -0.2617994f);
        this.Rwing1 = new ModelRenderer((ModelBase)this, 650, 1000);
        this.Rwing1.addBox(-87.0f, 0.0f, 0.0f, 87, 5, 5);
        this.Rwing1.setRotationPoint(-40.0f, -121.0f, -50.0f);
        this.Rwing1.setTextureSize(64, 32);
        this.Rwing1.mirror = true;
        this.setRotation(this.Rwing1, 0.0f, -0.0349066f, 0.0f);
        this.Rwing2 = new ModelRenderer((ModelBase)this, 1619, 782);
        this.Rwing2.addBox(-87.0f, 2.0f, 0.0f, 87, 1, 110);
        this.Rwing2.setRotationPoint(-40.0f, -121.0f, -49.0f);
        this.Rwing2.setTextureSize(64, 32);
        this.Rwing2.mirror = true;
        this.setRotation(this.Rwing2, 0.0f, -0.0349066f, 0.0f);
        this.Rwing3 = new ModelRenderer((ModelBase)this, 550, 950);
        this.Rwing3.addBox(-188.0f, 0.0f, 0.0f, 188, 5, 5);
        this.Rwing3.setRotationPoint(-124.0f, -121.0f, -53.0f);
        this.Rwing3.setTextureSize(64, 32);
        this.Rwing3.mirror = true;
        this.setRotation(this.Rwing3, 0.0f, 0.0f, 0.0f);
        this.Rwing4 = new ModelRenderer((ModelBase)this, 1341, 470);
        this.Rwing4.addBox(-188.0f, 2.0f, 0.0f, 188, 1, 147);
        this.Rwing4.setRotationPoint(-124.0f, -121.0f, -53.0f);
        this.Rwing4.setTextureSize(64, 32);
        this.Rwing4.mirror = true;
        this.setRotation(this.Rwing4, 0.0f, 0.0f, 0.0f);
        this.Rwing5 = new ModelRenderer((ModelBase)this, 750, 975);
        this.Rwing5.addBox(-87.0f, 0.0f, 0.0f, 87, 5, 5);
        this.Rwing5.setRotationPoint(-309.0f, -121.0f, -53.0f);
        this.Rwing5.setTextureSize(64, 32);
        this.Rwing5.mirror = true;
        this.setRotation(this.Rwing5, 0.0f, 0.0349066f, 0.0f);
        this.Rwing6 = new ModelRenderer((ModelBase)this, 1300, 1436);
        this.Rwing6.addBox(-87.0f, 2.0f, 1.0f, 87, 1, 125);
        this.Rwing6.setRotationPoint(-309.0f, -121.0f, -50.0f);
        this.Rwing6.setTextureSize(64, 32);
        this.Rwing6.mirror = true;
        this.setRotation(this.Rwing6, 0.0f, 0.0f, 0.0f);
        this.Rwing7 = new ModelRenderer((ModelBase)this, 650, 900);
        this.Rwing7.addBox(-150.0f, 0.0f, 0.0f, 150, 5, 5);
        this.Rwing7.setRotationPoint(-124.0f, -121.0f, -53.0f);
        this.Rwing7.setTextureSize(64, 32);
        this.Rwing7.mirror = true;
        this.setRotation(this.Rwing7, 0.0f, 0.0f, -0.2617994f);
        this.Rwing8 = new ModelRenderer((ModelBase)this, 1300, 1024);
        this.Rwing8.addBox(-150.0f, 2.0f, 0.0f, 150, 1, 120);
        this.Rwing8.setRotationPoint(-124.0f, -121.0f, -53.0f);
        this.Rwing8.setTextureSize(64, 32);
        this.Rwing8.mirror = true;
        this.setRotation(this.Rwing8, 0.0f, 0.0f, -0.2617994f);
        this.Rwing9 = new ModelRenderer((ModelBase)this, 621, 925);
        this.Rwing9.addBox(-175.0f, 0.0f, 0.0f, 175, 5, 5);
        this.Rwing9.setRotationPoint(-124.0f, -121.0f, -53.0f);
        this.Rwing9.setTextureSize(64, 32);
        this.Rwing9.mirror = true;
        this.setRotation(this.Rwing9, 0.0f, 0.0f, 0.2617994f);
        this.Rwing10 = new ModelRenderer((ModelBase)this, 1391, 184);
        this.Rwing10.addBox(-176.0f, 2.0f, 0.0f, 176, 1, 136);
        this.Rwing10.setRotationPoint(-124.0f, -121.0f, -53.0f);
        this.Rwing10.setTextureSize(64, 32);
        this.Rwing10.mirror = true;
        this.setRotation(this.Rwing10, 0.0f, 0.0f, 0.2617994f);
        this.TailTip2 = new ModelRenderer((ModelBase)this, 500, 63);
        this.TailTip2.addBox(-35.0f, -2.0f, 36.0f, 70, 4, 26);
        this.TailTip2.setRotationPoint(0.0f, -86.0f, 308.0f);
        this.TailTip2.setTextureSize(64, 32);
        this.TailTip2.mirror = true;
        this.setRotation(this.TailTip2, 0.0f, 0.0f, 0.0f);
        this.Ridge1 = new ModelRenderer((ModelBase)this, 850, 717);
        this.Ridge1.addBox(-1.0f, 0.0f, 0.0f, 3, 10, 24);
        this.Ridge1.setRotationPoint(0.0f, -122.0f, -75.0f);
        this.Ridge1.setTextureSize(64, 32);
        this.Ridge1.mirror = true;
        this.setRotation(this.Ridge1, 0.3665191f, 0.0f, 0.0f);
        this.Ridge2 = new ModelRenderer((ModelBase)this, 850, 676);
        this.Ridge2.addBox(-1.0f, 0.0f, 0.0f, 3, 10, 24);
        this.Ridge2.setRotationPoint(0.0f, -122.0f, -50.0f);
        this.Ridge2.setTextureSize(64, 32);
        this.Ridge2.mirror = true;
        this.setRotation(this.Ridge2, 0.3665191f, 0.0f, 0.0f);
        this.Ridge3 = new ModelRenderer((ModelBase)this, 800, 600);
        this.Ridge3.addBox(-1.0f, 0.0f, 0.0f, 3, 20, 49);
        this.Ridge3.setRotationPoint(0.0f, -120.0f, -20.0f);
        this.Ridge3.setTextureSize(64, 32);
        this.Ridge3.mirror = true;
        this.setRotation(this.Ridge3, 0.3665191f, 0.0f, 0.0f);
        this.Ridge4 = new ModelRenderer((ModelBase)this, 800, 550);
        this.Ridge4.addBox(-1.0f, 3.0f, 9.0f, 3, 10, 22);
        this.Ridge4.setRotationPoint(0.0f, -114.0f, 29.0f);
        this.Ridge4.setTextureSize(64, 32);
        this.Ridge4.mirror = true;
        this.setRotation(this.Ridge4, 0.3665191f, 0.0f, 0.0f);
        this.Ridge5 = new ModelRenderer((ModelBase)this, 800, 500);
        this.Ridge5.addBox(-1.0f, 13.0f, 33.0f, 3, 10, 20);
        this.Ridge5.setRotationPoint(0.0f, -114.0f, 29.0f);
        this.Ridge5.setTextureSize(64, 32);
        this.Ridge5.mirror = true;
        this.setRotation(this.Ridge5, 0.3665191f, 0.0f, 0.0f);
        this.Ridge6 = new ModelRenderer((ModelBase)this, 638, 165);
        this.Ridge6.addBox(-1.0f, 2.0f, 20.0f, 3, 10, 20);
        this.Ridge6.setRotationPoint(0.0f, -87.0f, 268.0f);
        this.Ridge6.setTextureSize(64, 32);
        this.Ridge6.mirror = true;
        this.setRotation(this.Ridge6, 0.3665191f, 0.0f, 0.0f);
    }

    public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5) {
        float newangle = 0.0f;
        TheKing k = (TheKing)entity;
        float tailspeed = 0.26f;
        float tailamp = 0.08f;
        float pi4 = 0.7853982f;
        float Lheadlr = 0.0f;
        float Lheadud = 0.0f;
        float Ljawangle = 0.0f;
        float Cheadlr = 0.0f;
        float Cheadud = 0.0f;
        float Cjawangle = 0.0f;
        float Rheadlr = 0.0f;
        float Rheadud = 0.0f;
        float Rjawangle = 0.0f;
        super.render(entity, f, f1, f2, f3, f4, f5);
        this.setRotationAngles(f, f1, f2, f3, f4, f5, entity);
        newangle = k.getAttacking() != 0 ? MathHelper.cos((float)(f2 * 0.75f * this.wingspeed)) * 3.1415927f * 0.21f : MathHelper.cos((float)(f2 * 0.35f * this.wingspeed)) * 3.1415927f * 0.15f;
        this.Lwing1.rotateAngleZ = newangle;
        this.Lwing2.rotateAngleZ = newangle;
        this.Lwing3.rotateAngleZ = newangle * 5.0f / 3.0f;
        this.Lwing3.rotationPointY = this.Lwing1.rotationPointY + (float)Math.sin(this.Lwing1.rotateAngleZ) * 84.0f;
        this.Lwing3.rotationPointX = this.Lwing1.rotationPointX + (float)Math.cos(this.Lwing1.rotateAngleZ) * 84.0f;
        this.Lwing4.rotateAngleZ = this.Lwing3.rotateAngleZ;
        this.Lwing4.rotationPointY = this.Lwing3.rotationPointY;
        this.Lwing4.rotationPointX = this.Lwing3.rotationPointX;
        this.Lwing5.rotateAngleZ = newangle * 7.0f / 3.0f;
        this.Lwing5.rotationPointY = this.Lwing3.rotationPointY + (float)Math.sin(this.Lwing3.rotateAngleZ) * 184.0f;
        this.Lwing5.rotationPointX = this.Lwing3.rotationPointX + (float)Math.cos(this.Lwing3.rotateAngleZ) * 184.0f;
        this.Lwing6.rotateAngleZ = this.Lwing5.rotateAngleZ;
        this.Lwing6.rotationPointY = this.Lwing5.rotationPointY;
        this.Lwing6.rotationPointX = this.Lwing5.rotationPointX;
        this.Lwing7.rotationPointY = this.Lwing9.rotationPointY = this.Lwing3.rotationPointY;
        this.Lwing7.rotationPointX = this.Lwing9.rotationPointX = this.Lwing3.rotationPointX;
        this.Lwing8.rotationPointY = this.Lwing10.rotationPointY = this.Lwing3.rotationPointY;
        this.Lwing8.rotationPointX = this.Lwing10.rotationPointX = this.Lwing3.rotationPointX;
        this.Lwing7.rotateAngleZ = this.Lwing8.rotateAngleZ = 0.261f + this.Lwing3.rotateAngleZ;
        this.Lwing9.rotateAngleZ = this.Lwing10.rotateAngleZ = -0.261f + this.Lwing3.rotateAngleZ;
        this.Rwing1.rotateAngleZ = - newangle;
        this.Rwing2.rotateAngleZ = - newangle;
        this.Rwing3.rotateAngleZ = (- newangle) * 5.0f / 3.0f;
        this.Rwing3.rotationPointY = this.Rwing1.rotationPointY - (float)Math.sin(this.Rwing1.rotateAngleZ) * 84.0f;
        this.Rwing3.rotationPointX = this.Rwing1.rotationPointX - (float)Math.cos(this.Rwing1.rotateAngleZ) * 84.0f;
        this.Rwing4.rotateAngleZ = this.Rwing3.rotateAngleZ;
        this.Rwing4.rotationPointY = this.Rwing3.rotationPointY;
        this.Rwing4.rotationPointX = this.Rwing3.rotationPointX;
        this.Rwing5.rotateAngleZ = (- newangle) * 7.0f / 3.0f;
        this.Rwing5.rotationPointY = this.Rwing3.rotationPointY - (float)Math.sin(this.Rwing3.rotateAngleZ) * 184.0f;
        this.Rwing5.rotationPointX = this.Rwing3.rotationPointX - (float)Math.cos(this.Rwing3.rotateAngleZ) * 184.0f;
        this.Rwing6.rotateAngleZ = this.Rwing5.rotateAngleZ;
        this.Rwing6.rotationPointY = this.Rwing5.rotationPointY;
        this.Rwing6.rotationPointX = this.Rwing5.rotationPointX;
        this.Rwing7.rotationPointY = this.Rwing9.rotationPointY = this.Rwing3.rotationPointY;
        this.Rwing7.rotationPointX = this.Rwing9.rotationPointX = this.Rwing3.rotationPointX;
        this.Rwing8.rotationPointY = this.Rwing10.rotationPointY = this.Rwing3.rotationPointY;
        this.Rwing8.rotationPointX = this.Rwing10.rotationPointX = this.Rwing3.rotationPointX;
        this.Rwing7.rotateAngleZ = this.Rwing8.rotateAngleZ = -0.261f + this.Rwing3.rotateAngleZ;
        this.Rwing9.rotateAngleZ = this.Rwing10.rotateAngleZ = 0.261f + this.Rwing3.rotateAngleZ;
        newangle = k.getAttacking() != 0 ? MathHelper.cos((float)(f2 * 0.75f * this.wingspeed)) * 3.1415927f * 0.25f : 0.0f;
        this.LClawRear.rotateAngleX = this.RClawRear.rotateAngleX = -0.925f + newangle;
        this.LLClaw1.rotateAngleX = 0.384f - newangle;
        this.LLClaw2.rotateAngleX = 0.645f - newangle;
        this.LCClaw1.rotateAngleX = 0.384f - newangle;
        this.LCClaw2.rotateAngleX = 0.645f - newangle;
        this.LRClaw1.rotateAngleX = 0.384f - newangle;
        this.LRClaw2.rotateAngleX = 0.645f - newangle;
        this.RLClaw1.rotateAngleX = 0.384f - newangle;
        this.RLClaw2.rotateAngleX = 0.645f - newangle;
        this.RCClaw1.rotateAngleX = 0.384f - newangle;
        this.RCClaw2.rotateAngleX = 0.645f - newangle;
        this.RRClaw1.rotateAngleX = 0.384f - newangle;
        this.RRClaw2.rotateAngleX = 0.645f - newangle;
        newangle = k.getAttacking() != 0 ? MathHelper.cos((float)(f2 * 0.6f * this.wingspeed)) * 3.1415927f * 0.45f : 0.0f;
        this.LThigh.rotateAngleX = this.LUpperLeg.rotateAngleX = 0.785f + newangle / 4.0f;
        this.LLowerLeg.rotateAngleX = this.LFoot.rotateAngleX = -0.628f + newangle / 2.0f;
        this.LLowerLeg.rotationPointY = this.LFoot.rotationPointY = this.LUpperLeg.rotationPointY + (float)Math.cos(this.LUpperLeg.rotateAngleX) * 50.0f;
        this.LLowerLeg.rotationPointZ = this.LFoot.rotationPointZ = this.LUpperLeg.rotationPointZ + (float)Math.sin(this.LUpperLeg.rotateAngleX) * 50.0f;
        this.LLClaw1.rotationPointY = this.LLClaw2.rotationPointY = this.LLowerLeg.rotationPointY + (float)Math.cos(this.LLowerLeg.rotateAngleX - 0.1f) * 66.0f;
        this.LLClaw1.rotationPointZ = this.LLClaw2.rotationPointZ = this.LLowerLeg.rotationPointZ + (float)Math.sin(this.LLowerLeg.rotateAngleX - 0.1f) * 66.0f;
        this.LCClaw1.rotationPointY = this.LCClaw2.rotationPointY = this.LLClaw1.rotationPointY;
        this.LRClaw1.rotationPointY = this.LRClaw2.rotationPointY = this.LLClaw1.rotationPointY;
        this.LCClaw1.rotationPointZ = this.LCClaw2.rotationPointZ = this.LLClaw1.rotationPointZ;
        this.LRClaw1.rotationPointZ = this.LRClaw2.rotationPointZ = this.LLClaw1.rotationPointZ;
        this.LClawRear.rotationPointY = this.LLowerLeg.rotationPointY + (float)Math.cos(this.LLowerLeg.rotateAngleX + 0.15f) * 66.0f;
        this.LClawRear.rotationPointZ = this.LLowerLeg.rotationPointZ + (float)Math.sin(this.LLowerLeg.rotateAngleX + 0.15f) * 66.0f;
        this.RThigh.rotateAngleX = this.RUpperLeg.rotateAngleX = 0.785f - newangle / 4.0f;
        this.RLowerLeg.rotateAngleX = this.RFoot.rotateAngleX = -0.628f - newangle / 2.0f;
        this.RLowerLeg.rotationPointY = this.RFoot.rotationPointY = this.RUpperLeg.rotationPointY + (float)Math.cos(this.RUpperLeg.rotateAngleX) * 50.0f;
        this.RLowerLeg.rotationPointZ = this.RFoot.rotationPointZ = this.RUpperLeg.rotationPointZ + (float)Math.sin(this.RUpperLeg.rotateAngleX) * 50.0f;
        this.RLClaw1.rotationPointY = this.RLClaw2.rotationPointY = this.RLowerLeg.rotationPointY + (float)Math.cos(this.RLowerLeg.rotateAngleX - 0.1f) * 66.0f;
        this.RLClaw1.rotationPointZ = this.RLClaw2.rotationPointZ = this.RLowerLeg.rotationPointZ + (float)Math.sin(this.RLowerLeg.rotateAngleX - 0.1f) * 66.0f;
        this.RCClaw1.rotationPointY = this.RCClaw2.rotationPointY = this.RLClaw1.rotationPointY;
        this.RRClaw1.rotationPointY = this.RRClaw2.rotationPointY = this.RLClaw1.rotationPointY;
        this.RCClaw1.rotationPointZ = this.RCClaw2.rotationPointZ = this.RLClaw1.rotationPointZ;
        this.RRClaw1.rotationPointZ = this.RRClaw2.rotationPointZ = this.RLClaw1.rotationPointZ;
        this.RClawRear.rotationPointY = this.RLowerLeg.rotationPointY + (float)Math.cos(this.RLowerLeg.rotateAngleX + 0.15f) * 66.0f;
        this.RClawRear.rotationPointZ = this.RLowerLeg.rotationPointZ + (float)Math.sin(this.RLowerLeg.rotateAngleX + 0.15f) * 66.0f;
        if (k.getAttacking() != 0) {
            tailspeed = 0.56f;
            tailamp = 0.19f;
        }
        this.Ridge4.rotateAngleY = this.Ridge5.rotateAngleY = (this.Tail1.rotateAngleY = MathHelper.cos((float)(f2 * tailspeed * this.wingspeed)) * 3.1415927f * tailamp / 2.0f);
        this.Tail2.rotationPointZ = this.Tail1.rotationPointZ + (float)Math.cos(this.Tail1.rotateAngleY) * 54.0f;
        this.Tail2.rotationPointX = this.Tail1.rotationPointX - 1.0f + (float)Math.sin(this.Tail1.rotateAngleY) * 54.0f;
        this.Tail2.rotateAngleY = MathHelper.cos((float)(f2 * tailspeed * this.wingspeed - pi4)) * 3.1415927f * tailamp;
        this.Tail3.rotationPointZ = this.Tail2.rotationPointZ + (float)Math.cos(this.Tail2.rotateAngleY) * 42.0f;
        this.Tail3.rotationPointX = this.Tail2.rotationPointX + (float)Math.sin(this.Tail2.rotateAngleY) * 42.0f;
        this.Tail3.rotateAngleY = MathHelper.cos((float)(f2 * tailspeed * this.wingspeed - 2.0f * pi4)) * 3.1415927f * tailamp;
        this.Tail4.rotationPointZ = this.Tail3.rotationPointZ + (float)Math.cos(this.Tail3.rotateAngleY) * 41.0f;
        this.Tail4.rotationPointX = this.Tail3.rotationPointX + (float)Math.sin(this.Tail3.rotateAngleY) * 41.0f;
        this.Tail4.rotateAngleY = MathHelper.cos((float)(f2 * tailspeed * this.wingspeed - 3.0f * pi4)) * 3.1415927f * tailamp;
        newangle = MathHelper.cos((float)(f2 * tailspeed * this.wingspeed - 3.0f * pi4)) * 3.1415927f * tailamp;
        this.Tail5.rotationPointZ = this.Tail4.rotationPointZ + (float)Math.cos(this.Tail4.rotateAngleY) * 34.0f;
        this.Tail5.rotationPointX = this.Tail4.rotationPointX + (float)Math.sin(this.Tail4.rotateAngleY) * 34.0f;
        this.Tail5.rotateAngleY = this.Tail4.rotateAngleY + (newangle /= 2.0f);
        this.Tail6.rotationPointZ = this.Tail5.rotationPointZ + (float)Math.cos(this.Tail5.rotateAngleY) * 34.0f;
        this.Tail6.rotationPointX = this.Tail5.rotationPointX + (float)Math.sin(this.Tail5.rotateAngleY) * 34.0f;
        this.Tail6.rotateAngleY = this.Tail5.rotateAngleY + newangle;
        this.Tail7.rotationPointZ = this.Ridge6.rotationPointZ = this.Tail6.rotationPointZ + (float)Math.cos(this.Tail6.rotateAngleY) * 40.0f;
        this.Tail7.rotationPointX = this.Ridge6.rotationPointX = this.Tail6.rotationPointX + (float)Math.sin(this.Tail6.rotateAngleY) * 40.0f;
        this.Tail7.rotateAngleY = this.Ridge6.rotateAngleY = this.Tail6.rotateAngleY + newangle;
        this.TailTip.rotationPointZ = this.TailTip2.rotationPointZ = this.Tail7.rotationPointZ + (float)Math.cos(this.Tail7.rotateAngleY) * 43.0f;
        this.TailTip.rotationPointX = this.TailTip2.rotationPointX = this.Tail7.rotationPointX + (float)Math.sin(this.Tail7.rotateAngleY) * 43.0f;
        this.TailTip.rotateAngleY = this.TailTip2.rotateAngleY = this.Tail7.rotateAngleY + newangle;
        this.TailSpike.rotationPointZ = this.TailTip.rotationPointZ + (float)Math.cos(this.TailTip.rotateAngleY) * 58.0f;
        this.TailSpike.rotationPointX = this.TailTip.rotationPointX + (float)Math.sin(this.TailTip.rotateAngleY) * 58.0f;
        this.TailSpike.rotateAngleY = this.TailTip.rotateAngleY + newangle;
        if (k.getAttacking() != 0) {
            Lheadlr = MathHelper.sin((float)(f2 * 0.3f * this.wingspeed)) * 3.1415927f * 0.25f;
            Lheadud = MathHelper.sin((float)(f2 * 0.2f * this.wingspeed)) * 3.1415927f * 0.25f;
            Ljawangle = MathHelper.sin((float)(f2 * 0.85f * this.wingspeed)) * 3.1415927f * 0.12f;
            Rheadlr = MathHelper.sin((float)(f2 * 0.32f * this.wingspeed)) * 3.1415927f * 0.25f;
            Rheadud = MathHelper.sin((float)(f2 * 0.21f * this.wingspeed)) * 3.1415927f * 0.25f;
            Rjawangle = MathHelper.sin((float)(f2 * 0.95f * this.wingspeed)) * 3.1415927f * 0.12f;
            Cheadlr = MathHelper.sin((float)(f2 * 0.28f * this.wingspeed)) * 3.1415927f * 0.25f;
            Cheadud = MathHelper.sin((float)(f2 * 0.19f * this.wingspeed)) * 3.1415927f * 0.25f;
            Cjawangle = MathHelper.sin((float)(f2 * 0.75f * this.wingspeed)) * 3.1415927f * 0.12f;
            Ljawangle += 0.5f;
            Ljawangle += Lheadud;
            Cjawangle += 0.5f;
            Cjawangle += Cheadud;
            Rjawangle += 0.5f;
            Rjawangle += Rheadud;
        } else {
            Lheadlr = MathHelper.sin((float)(f2 * 0.17f * this.wingspeed)) * 3.1415927f * 0.08f;
            Lheadud = MathHelper.sin((float)(f2 * 0.13f * this.wingspeed)) * 3.1415927f * 0.1f;
            Ljawangle = MathHelper.sin((float)(f2 * 0.45f * this.wingspeed)) * 3.1415927f * 0.04f;
            Rheadlr = MathHelper.sin((float)(f2 * 0.19f * this.wingspeed)) * 3.1415927f * 0.08f;
            Rheadud = MathHelper.sin((float)(f2 * 0.12f * this.wingspeed)) * 3.1415927f * 0.1f;
            Rjawangle = MathHelper.sin((float)(f2 * 0.55f * this.wingspeed)) * 3.1415927f * 0.04f;
            Cheadlr = MathHelper.sin((float)(f2 * 0.13f * this.wingspeed)) * 3.1415927f * 0.08f;
            Cheadud = MathHelper.sin((float)(f2 * 0.08f * this.wingspeed)) * 3.1415927f * 0.1f;
            Cjawangle = MathHelper.sin((float)(f2 * 0.65f * this.wingspeed)) * 3.1415927f * 0.04f;
            Ljawangle += 0.25f;
            Ljawangle += Lheadud;
            Cjawangle += 0.25f;
            Cjawangle += Cheadud;
            Rjawangle += 0.25f;
            Rjawangle += Rheadud;
        }
        if (Lheadlr > Cheadlr) {
            Lheadlr = Cheadlr;
        }
        if (Rheadlr < Cheadlr) {
            Rheadlr = Cheadlr;
        }
        this.moveLeftHead(Lheadlr, Lheadud, Ljawangle);
        this.moveCenterHead(Cheadlr, Cheadud, Cjawangle);
        this.moveRightHead(Rheadlr, Rheadud, Rjawangle);
        this.LCClaw1.render(f5);
        this.LThigh.render(f5);
        this.LUpperLeg.render(f5);
        this.TailTip.render(f5);
        this.Tail1.render(f5);
        this.Tail2.render(f5);
        this.Tail3.render(f5);
        this.Tail4.render(f5);
        this.Tail5.render(f5);
        this.Tail6.render(f5);
        this.Tail7.render(f5);
        this.Body1.render(f5);
        this.Chest.render(f5);
        this.NeckC1.render(f5);
        this.LLowerLeg.render(f5);
        this.LFoot.render(f5);
        this.LLClaw1.render(f5);
        this.LRClaw1.render(f5);
        this.LCClaw2.render(f5);
        this.LLClaw2.render(f5);
        this.TailSpike.render(f5);
        this.LRClaw2.render(f5);
        this.LClawRear.render(f5);
        this.NeckL1.render(f5);
        this.NeckR1.render(f5);
        this.RThigh.render(f5);
        this.RUpperLeg.render(f5);
        this.RLowerLeg.render(f5);
        this.RFoot.render(f5);
        this.RClawRear.render(f5);
        this.RLClaw1.render(f5);
        this.RCClaw1.render(f5);
        this.RRClaw1.render(f5);
        this.RLClaw2.render(f5);
        this.RCClaw2.render(f5);
        this.RRClaw2.render(f5);
        this.NeckL2.render(f5);
        this.NeckC2.render(f5);
        this.NeckR2.render(f5);
        this.NeckL3.render(f5);
        this.NeckC3.render(f5);
        this.NeckR3.render(f5);
        this.NeckL4.render(f5);
        this.LHead1.render(f5);
        this.LHead2.render(f5);
        this.LHead3.render(f5);
        this.LJaw1.render(f5);
        this.LJaw2.render(f5);
        this.LJaw3.render(f5);
        this.LTooth1.render(f5);
        this.LTooth2.render(f5);
        this.LTooth3.render(f5);
        this.LTooth4.render(f5);
        this.NeckC4.render(f5);
        this.NeckR4.render(f5);
        this.CHead1.render(f5);
        this.RHead1.render(f5);
        this.CHead2.render(f5);
        this.RHead2.render(f5);
        this.CHead3.render(f5);
        this.RHead3.render(f5);
        this.CJaw1.render(f5);
        this.CJaw2.render(f5);
        this.CJaw3.render(f5);
        this.RJaw1.render(f5);
        this.RJaw2.render(f5);
        this.RJaw3.render(f5);
        this.CTooth3.render(f5);
        this.CTooth4.render(f5);
        this.CTooth1.render(f5);
        this.CTooth2.render(f5);
        this.RTooth3.render(f5);
        this.RTooth4.render(f5);
        this.RTooth1.render(f5);
        this.RTooth2.render(f5);
        this.LLEye.render(f5);
        this.LREye.render(f5);
        this.CLEye.render(f5);
        this.CREye.render(f5);
        this.RLEye.render(f5);
        this.RREye.render(f5);
        this.LHeadMane.render(f5);
        this.CHeadMane.render(f5);
        this.RHeadMane.render(f5);
        this.LLNoseSpike.render(f5);
        this.LRNoseSpike.render(f5);
        this.CLNoseSpike.render(f5);
        this.CRNoseSpike.render(f5);
        this.RLNoseSpike.render(f5);
        this.RRNoseSpike.render(f5);
        this.Back1.render(f5);
        this.Back2.render(f5);
        this.Lwing1.render(f5);
        this.Lwing3.render(f5);
        this.Lwing5.render(f5);
        this.Lwing7.render(f5);
        this.Lwing9.render(f5);
        this.Rwing1.render(f5);
        this.Rwing3.render(f5);
        this.Rwing5.render(f5);
        this.Rwing7.render(f5);
        this.Rwing9.render(f5);
        this.TailTip2.render(f5);
        this.Ridge1.render(f5);
        this.Ridge2.render(f5);
        this.Ridge3.render(f5);
        this.Ridge4.render(f5);
        this.Ridge5.render(f5);
        this.Ridge6.render(f5);
        GL11.glPushMatrix();
        GL11.glEnable((int)2977);
        GL11.glEnable((int)3042);
        GL11.glBlendFunc((int)770, (int)771);
        GL11.glColor4f((float)0.75f, (float)0.75f, (float)0.75f, (float)0.55f);
        this.Lwing2.render(f5);
        this.Lwing4.render(f5);
        this.Lwing6.render(f5);
        this.Lwing8.render(f5);
        this.Lwing10.render(f5);
        this.Rwing2.render(f5);
        this.Rwing4.render(f5);
        this.Rwing6.render(f5);
        this.Rwing8.render(f5);
        this.Rwing10.render(f5);
        GL11.glDisable((int)3042);
        GL11.glPopMatrix();
    }

    private void setRotation(ModelRenderer model, float x, float y, float z) {
        model.rotateAngleX = x;
        model.rotateAngleY = y;
        model.rotateAngleZ = z;
    }

    public void setRotationAngles(float par1, float par2, float par3, float par4, float par5, float par6, Entity par7Entity) {
        super.setRotationAngles(par1, par2, par3, par4, par5, par6, par7Entity);
    }

    private void moveLeftHead(float Lheadlr, float Lheadud, float Ljawangle) {
        this.LJaw1.rotateAngleX = Ljawangle;
        this.LJaw2.rotateAngleX = Ljawangle;
        this.LJaw3.rotateAngleX = Ljawangle;
        this.LTooth1.rotateAngleX = Ljawangle;
        this.LTooth2.rotateAngleX = Ljawangle;
        this.LTooth3.rotateAngleX = Ljawangle;
        this.LTooth4.rotateAngleX = Ljawangle;
        this.NeckL1.rotateAngleY = Lheadlr * 0.125f;
        this.NeckL2.rotationPointZ = this.NeckL1.rotationPointZ - (float)Math.cos(this.NeckL1.rotateAngleY) * 20.0f;
        this.NeckL2.rotationPointX = this.NeckL1.rotationPointX - (float)Math.sin(this.NeckL1.rotateAngleY) * 20.0f;
        this.NeckL2.rotateAngleY = Lheadlr * 0.25f;
        this.NeckL3.rotationPointZ = this.NeckL2.rotationPointZ - (float)Math.cos(this.NeckL2.rotateAngleY) * 36.0f;
        this.NeckL3.rotationPointX = this.NeckL2.rotationPointX - (float)Math.sin(this.NeckL2.rotateAngleY) * 36.0f;
        this.NeckL3.rotateAngleY = Lheadlr * 0.38f;
        this.NeckL4.rotationPointZ = this.NeckL3.rotationPointZ - (float)Math.cos(this.NeckL3.rotateAngleY) * 36.0f;
        this.NeckL4.rotationPointX = this.NeckL3.rotationPointX - (float)Math.sin(this.NeckL3.rotateAngleY) * 36.0f;
        this.NeckL4.rotateAngleY = Lheadlr * 0.5f;
        this.LHead1.rotationPointZ = this.NeckL4.rotationPointZ - (float)Math.cos(this.NeckL4.rotateAngleY) * 36.0f;
        this.LHead1.rotationPointX = this.NeckL4.rotationPointX - (float)Math.sin(this.NeckL4.rotateAngleY) * 36.0f;
        this.LHead1.rotateAngleY = Lheadlr;
        this.LHead2.rotateAngleY = Lheadlr;
        this.LHead2.rotationPointZ = this.LHead1.rotationPointZ;
        this.LHead2.rotationPointX = this.LHead1.rotationPointX;
        this.LHead3.rotateAngleY = Lheadlr;
        this.LHead3.rotationPointZ = this.LHead1.rotationPointZ;
        this.LHead3.rotationPointX = this.LHead1.rotationPointX;
        this.LHeadMane.rotateAngleY = Lheadlr;
        this.LHeadMane.rotationPointZ = this.LHead1.rotationPointZ;
        this.LHeadMane.rotationPointX = this.LHead1.rotationPointX;
        this.LLEye.rotateAngleY = Lheadlr;
        this.LLEye.rotationPointZ = this.LHead1.rotationPointZ;
        this.LLEye.rotationPointX = this.LHead1.rotationPointX;
        this.LREye.rotateAngleY = Lheadlr;
        this.LREye.rotationPointZ = this.LHead1.rotationPointZ;
        this.LREye.rotationPointX = this.LHead1.rotationPointX;
        this.LLNoseSpike.rotateAngleY = 0.244f + Lheadlr;
        this.LLNoseSpike.rotationPointZ = this.LHead1.rotationPointZ;
        this.LLNoseSpike.rotationPointX = this.LHead1.rotationPointX;
        this.LRNoseSpike.rotateAngleY = -0.261f + Lheadlr;
        this.LRNoseSpike.rotationPointZ = this.LHead1.rotationPointZ;
        this.LRNoseSpike.rotationPointX = this.LHead1.rotationPointX;
        this.LJaw1.rotateAngleY = Lheadlr;
        this.LJaw1.rotationPointZ = this.NeckL4.rotationPointZ - (float)Math.cos(this.NeckL4.rotateAngleY) * 37.0f;
        this.LJaw1.rotationPointX = this.NeckL4.rotationPointX - (float)Math.sin(this.NeckL4.rotateAngleY) * 37.0f;
        this.LJaw2.rotateAngleY = Lheadlr;
        this.LJaw2.rotationPointZ = this.LJaw1.rotationPointZ;
        this.LJaw2.rotationPointX = this.LJaw1.rotationPointX;
        this.LJaw3.rotateAngleY = Lheadlr;
        this.LJaw3.rotationPointZ = this.LJaw1.rotationPointZ;
        this.LJaw3.rotationPointX = this.LJaw1.rotationPointX;
        this.LTooth1.rotateAngleY = Lheadlr;
        this.LTooth1.rotationPointZ = this.LJaw1.rotationPointZ;
        this.LTooth1.rotationPointX = this.LJaw1.rotationPointX;
        this.LTooth2.rotateAngleY = Lheadlr;
        this.LTooth2.rotationPointZ = this.LJaw1.rotationPointZ;
        this.LTooth2.rotationPointX = this.LJaw1.rotationPointX;
        this.LTooth3.rotateAngleY = Lheadlr;
        this.LTooth3.rotationPointZ = this.LJaw1.rotationPointZ;
        this.LTooth3.rotationPointX = this.LJaw1.rotationPointX;
        this.LTooth4.rotateAngleY = Lheadlr;
        this.LTooth4.rotationPointZ = this.LJaw1.rotationPointZ;
        this.LTooth4.rotationPointX = this.LJaw1.rotationPointX;
        this.NeckL1.rotateAngleX = Lheadud * 0.125f;
        this.NeckL2.rotationPointY = this.NeckL1.rotationPointY + (float)Math.sin(this.NeckL1.rotateAngleX) * 20.0f;
        this.NeckL2.rotationPointZ = this.NeckL1.rotationPointZ + (this.NeckL2.rotationPointZ - this.NeckL1.rotationPointZ) * (float)Math.cos(this.NeckL1.rotateAngleX);
        this.NeckL2.rotationPointX = this.NeckL1.rotationPointX + (this.NeckL2.rotationPointX - this.NeckL1.rotationPointX) * (float)Math.cos(this.NeckL1.rotateAngleX);
        this.NeckL2.rotateAngleX = Lheadud * 0.25f;
        this.NeckL3.rotationPointY = this.NeckL2.rotationPointY + (float)Math.sin(this.NeckL2.rotateAngleX) * 36.0f;
        this.NeckL3.rotationPointZ = this.NeckL2.rotationPointZ + (this.NeckL3.rotationPointZ - this.NeckL2.rotationPointZ) * (float)Math.cos(this.NeckL2.rotateAngleX);
        this.NeckL3.rotationPointX = this.NeckL2.rotationPointX + (this.NeckL3.rotationPointX - this.NeckL2.rotationPointX) * (float)Math.cos(this.NeckL2.rotateAngleX);
        this.NeckL3.rotateAngleX = Lheadud * 0.38f;
        this.NeckL4.rotationPointY = this.NeckL3.rotationPointY + (float)Math.sin(this.NeckL3.rotateAngleX) * 36.0f;
        this.NeckL4.rotationPointZ = this.NeckL3.rotationPointZ + (this.NeckL4.rotationPointZ - this.NeckL3.rotationPointZ) * (float)Math.cos(this.NeckL3.rotateAngleX);
        this.NeckL4.rotationPointX = this.NeckL3.rotationPointX + (this.NeckL4.rotationPointX - this.NeckL3.rotationPointX) * (float)Math.cos(this.NeckL3.rotateAngleX);
        this.NeckL4.rotateAngleX = Lheadud * 0.5f;
        this.LHead1.rotationPointY = this.NeckL4.rotationPointY + (float)Math.sin(this.NeckL4.rotateAngleX) * 36.0f;
        this.LHead1.rotationPointZ = this.NeckL4.rotationPointZ + (this.LHead1.rotationPointZ - this.NeckL4.rotationPointZ) * (float)Math.cos(this.NeckL4.rotateAngleX);
        this.LHead1.rotationPointX = this.NeckL4.rotationPointX + (this.LHead1.rotationPointX - this.NeckL4.rotationPointX) * (float)Math.cos(this.NeckL4.rotateAngleX);
        this.LHead1.rotateAngleX = Lheadud;
        this.LHead2.rotateAngleX = Lheadud;
        this.LHead2.rotationPointZ = this.LHead1.rotationPointZ;
        this.LHead2.rotationPointX = this.LHead1.rotationPointX;
        this.LHead2.rotationPointY = this.LHead1.rotationPointY;
        this.LHead3.rotateAngleX = Lheadud;
        this.LHead3.rotationPointZ = this.LHead1.rotationPointZ;
        this.LHead3.rotationPointX = this.LHead1.rotationPointX;
        this.LHead3.rotationPointY = this.LHead1.rotationPointY;
        this.LHeadMane.rotateAngleX = 0.384f + Lheadud;
        this.LHeadMane.rotationPointZ = this.LHead1.rotationPointZ;
        this.LHeadMane.rotationPointX = this.LHead1.rotationPointX;
        this.LHeadMane.rotationPointY = this.LHead1.rotationPointY;
        this.LLEye.rotateAngleX = Lheadud;
        this.LLEye.rotationPointZ = this.LHead1.rotationPointZ;
        this.LLEye.rotationPointX = this.LHead1.rotationPointX;
        this.LLEye.rotationPointY = this.LHead1.rotationPointY;
        this.LREye.rotateAngleX = Lheadud;
        this.LREye.rotationPointZ = this.LHead1.rotationPointZ;
        this.LREye.rotationPointX = this.LHead1.rotationPointX;
        this.LREye.rotationPointY = this.LHead1.rotationPointY;
        this.LLNoseSpike.rotateAngleX = 0.244f + Lheadud;
        this.LLNoseSpike.rotationPointZ = this.LHead1.rotationPointZ;
        this.LLNoseSpike.rotationPointX = this.LHead1.rotationPointX;
        this.LLNoseSpike.rotationPointY = this.LHead1.rotationPointY;
        this.LRNoseSpike.rotateAngleX = 0.261f + Lheadud;
        this.LRNoseSpike.rotationPointZ = this.LHead1.rotationPointZ;
        this.LRNoseSpike.rotationPointX = this.LHead1.rotationPointX;
        this.LRNoseSpike.rotationPointY = this.LHead1.rotationPointY;
        this.LJaw1.rotationPointY = this.LHead1.rotationPointY + (float)Math.cos(this.LHead1.rotateAngleX) * 14.0f;
        this.LJaw1.rotationPointZ = this.NeckL4.rotationPointZ + (this.LJaw1.rotationPointZ - this.NeckL4.rotationPointZ) * (float)Math.cos(this.NeckL4.rotateAngleX);
        this.LJaw1.rotationPointZ += (float)Math.sin(this.LHead1.rotateAngleX) * 14.0f;
        this.LJaw1.rotationPointX = this.NeckL4.rotationPointX + (this.LJaw1.rotationPointX - this.NeckL4.rotationPointX) * (float)Math.cos(this.NeckL4.rotateAngleX);
        this.LJaw2.rotationPointZ = this.LJaw1.rotationPointZ;
        this.LJaw2.rotationPointX = this.LJaw1.rotationPointX;
        this.LJaw2.rotationPointY = this.LJaw1.rotationPointY;
        this.LJaw3.rotationPointZ = this.LJaw1.rotationPointZ;
        this.LJaw3.rotationPointX = this.LJaw1.rotationPointX;
        this.LJaw3.rotationPointY = this.LJaw1.rotationPointY;
        this.LTooth1.rotationPointZ = this.LJaw1.rotationPointZ;
        this.LTooth1.rotationPointX = this.LJaw1.rotationPointX;
        this.LTooth1.rotationPointY = this.LJaw1.rotationPointY;
        this.LTooth2.rotationPointZ = this.LJaw1.rotationPointZ;
        this.LTooth2.rotationPointX = this.LJaw1.rotationPointX;
        this.LTooth2.rotationPointY = this.LJaw1.rotationPointY;
        this.LTooth3.rotationPointZ = this.LJaw1.rotationPointZ;
        this.LTooth3.rotationPointX = this.LJaw1.rotationPointX;
        this.LTooth3.rotationPointY = this.LJaw1.rotationPointY;
        this.LTooth4.rotationPointZ = this.LJaw1.rotationPointZ;
        this.LTooth4.rotationPointX = this.LJaw1.rotationPointX;
        this.LTooth4.rotationPointY = this.LJaw1.rotationPointY;
    }

    private void moveCenterHead(float Cheadlr, float Cheadud, float Cjawangle) {
        this.CJaw1.rotateAngleX = Cjawangle;
        this.CJaw2.rotateAngleX = Cjawangle;
        this.CJaw3.rotateAngleX = Cjawangle;
        this.CTooth1.rotateAngleX = Cjawangle;
        this.CTooth2.rotateAngleX = Cjawangle;
        this.CTooth3.rotateAngleX = Cjawangle;
        this.CTooth4.rotateAngleX = Cjawangle;
        this.NeckC1.rotateAngleY = Cheadlr * 0.125f;
        this.NeckC2.rotationPointZ = this.NeckC1.rotationPointZ - (float)Math.cos(this.NeckC1.rotateAngleY) * 20.0f;
        this.NeckC2.rotationPointX = this.NeckC1.rotationPointX - (float)Math.sin(this.NeckC1.rotateAngleY) * 20.0f;
        this.NeckC2.rotateAngleY = Cheadlr * 0.25f;
        this.NeckC3.rotationPointZ = this.NeckC2.rotationPointZ - (float)Math.cos(this.NeckC2.rotateAngleY) * 36.0f;
        this.NeckC3.rotationPointX = this.NeckC2.rotationPointX - (float)Math.sin(this.NeckC2.rotateAngleY) * 36.0f;
        this.NeckC3.rotateAngleY = Cheadlr * 0.38f;
        this.NeckC4.rotationPointZ = this.NeckC3.rotationPointZ - (float)Math.cos(this.NeckC3.rotateAngleY) * 36.0f;
        this.NeckC4.rotationPointX = this.NeckC3.rotationPointX - (float)Math.sin(this.NeckC3.rotateAngleY) * 36.0f;
        this.NeckC4.rotateAngleY = Cheadlr * 0.5f;
        this.CHead1.rotationPointZ = this.NeckC4.rotationPointZ - (float)Math.cos(this.NeckC4.rotateAngleY) * 36.0f;
        this.CHead1.rotationPointX = this.NeckC4.rotationPointX - (float)Math.sin(this.NeckC4.rotateAngleY) * 36.0f;
        this.CHead1.rotateAngleY = Cheadlr;
        this.CHead2.rotateAngleY = Cheadlr;
        this.CHead2.rotationPointZ = this.CHead1.rotationPointZ;
        this.CHead2.rotationPointX = this.CHead1.rotationPointX;
        this.CHead3.rotateAngleY = Cheadlr;
        this.CHead3.rotationPointZ = this.CHead1.rotationPointZ;
        this.CHead3.rotationPointX = this.CHead1.rotationPointX;
        this.CHeadMane.rotateAngleY = Cheadlr;
        this.CHeadMane.rotationPointZ = this.CHead1.rotationPointZ;
        this.CHeadMane.rotationPointX = this.CHead1.rotationPointX;
        this.CLEye.rotateAngleY = Cheadlr;
        this.CLEye.rotationPointZ = this.CHead1.rotationPointZ;
        this.CLEye.rotationPointX = this.CHead1.rotationPointX;
        this.CREye.rotateAngleY = Cheadlr;
        this.CREye.rotationPointZ = this.CHead1.rotationPointZ;
        this.CREye.rotationPointX = this.CHead1.rotationPointX;
        this.CLNoseSpike.rotateAngleY = 0.244f + Cheadlr;
        this.CLNoseSpike.rotationPointZ = this.CHead1.rotationPointZ;
        this.CLNoseSpike.rotationPointX = this.CHead1.rotationPointX;
        this.CRNoseSpike.rotateAngleY = -0.261f + Cheadlr;
        this.CRNoseSpike.rotationPointZ = this.CHead1.rotationPointZ;
        this.CRNoseSpike.rotationPointX = this.CHead1.rotationPointX;
        this.CJaw1.rotateAngleY = Cheadlr;
        this.CJaw1.rotationPointZ = this.NeckC4.rotationPointZ - (float)Math.cos(this.NeckC4.rotateAngleY) * 37.0f;
        this.CJaw1.rotationPointX = this.NeckC4.rotationPointX - (float)Math.sin(this.NeckC4.rotateAngleY) * 37.0f;
        this.CJaw2.rotateAngleY = Cheadlr;
        this.CJaw2.rotationPointZ = this.CJaw1.rotationPointZ;
        this.CJaw2.rotationPointX = this.CJaw1.rotationPointX;
        this.CJaw3.rotateAngleY = Cheadlr;
        this.CJaw3.rotationPointZ = this.CJaw1.rotationPointZ;
        this.CJaw3.rotationPointX = this.CJaw1.rotationPointX;
        this.CTooth1.rotateAngleY = Cheadlr;
        this.CTooth1.rotationPointZ = this.CJaw1.rotationPointZ;
        this.CTooth1.rotationPointX = this.CJaw1.rotationPointX;
        this.CTooth2.rotateAngleY = Cheadlr;
        this.CTooth2.rotationPointZ = this.CJaw1.rotationPointZ;
        this.CTooth2.rotationPointX = this.CJaw1.rotationPointX;
        this.CTooth3.rotateAngleY = Cheadlr;
        this.CTooth3.rotationPointZ = this.CJaw1.rotationPointZ;
        this.CTooth3.rotationPointX = this.CJaw1.rotationPointX;
        this.CTooth4.rotateAngleY = Cheadlr;
        this.CTooth4.rotationPointZ = this.CJaw1.rotationPointZ;
        this.CTooth4.rotationPointX = this.CJaw1.rotationPointX;
        this.NeckC1.rotateAngleX = Cheadud * 0.125f;
        this.NeckC2.rotationPointY = this.NeckC1.rotationPointY + (float)Math.sin(this.NeckC1.rotateAngleX) * 20.0f;
        this.NeckC2.rotationPointZ = this.NeckC1.rotationPointZ + (this.NeckC2.rotationPointZ - this.NeckC1.rotationPointZ) * (float)Math.cos(this.NeckC1.rotateAngleX);
        this.NeckC2.rotationPointX = this.NeckC1.rotationPointX + (this.NeckC2.rotationPointX - this.NeckC1.rotationPointX) * (float)Math.cos(this.NeckC1.rotateAngleX);
        this.NeckC2.rotateAngleX = Cheadud * 0.25f;
        this.NeckC3.rotationPointY = this.NeckC2.rotationPointY + (float)Math.sin(this.NeckC2.rotateAngleX) * 36.0f;
        this.NeckC3.rotationPointZ = this.NeckC2.rotationPointZ + (this.NeckC3.rotationPointZ - this.NeckC2.rotationPointZ) * (float)Math.cos(this.NeckC2.rotateAngleX);
        this.NeckC3.rotationPointX = this.NeckC2.rotationPointX + (this.NeckC3.rotationPointX - this.NeckC2.rotationPointX) * (float)Math.cos(this.NeckC2.rotateAngleX);
        this.NeckC3.rotateAngleX = Cheadud * 0.38f;
        this.NeckC4.rotationPointY = this.NeckC3.rotationPointY + (float)Math.sin(this.NeckC3.rotateAngleX) * 36.0f;
        this.NeckC4.rotationPointZ = this.NeckC3.rotationPointZ + (this.NeckC4.rotationPointZ - this.NeckC3.rotationPointZ) * (float)Math.cos(this.NeckC3.rotateAngleX);
        this.NeckC4.rotationPointX = this.NeckC3.rotationPointX + (this.NeckC4.rotationPointX - this.NeckC3.rotationPointX) * (float)Math.cos(this.NeckC3.rotateAngleX);
        this.NeckC4.rotateAngleX = Cheadud * 0.5f;
        this.CHead1.rotationPointY = this.NeckC4.rotationPointY + (float)Math.sin(this.NeckC4.rotateAngleX) * 36.0f;
        this.CHead1.rotationPointZ = this.NeckC4.rotationPointZ + (this.CHead1.rotationPointZ - this.NeckC4.rotationPointZ) * (float)Math.cos(this.NeckC4.rotateAngleX);
        this.CHead1.rotationPointX = this.NeckC4.rotationPointX + (this.CHead1.rotationPointX - this.NeckC4.rotationPointX) * (float)Math.cos(this.NeckC4.rotateAngleX);
        this.CHead1.rotateAngleX = Cheadud;
        this.CHead2.rotateAngleX = Cheadud;
        this.CHead2.rotationPointZ = this.CHead1.rotationPointZ;
        this.CHead2.rotationPointX = this.CHead1.rotationPointX;
        this.CHead2.rotationPointY = this.CHead1.rotationPointY;
        this.CHead3.rotateAngleX = Cheadud;
        this.CHead3.rotationPointZ = this.CHead1.rotationPointZ;
        this.CHead3.rotationPointX = this.CHead1.rotationPointX;
        this.CHead3.rotationPointY = this.CHead1.rotationPointY;
        this.CHeadMane.rotateAngleX = 0.384f + Cheadud;
        this.CHeadMane.rotationPointZ = this.CHead1.rotationPointZ;
        this.CHeadMane.rotationPointX = this.CHead1.rotationPointX;
        this.CHeadMane.rotationPointY = this.CHead1.rotationPointY;
        this.CLEye.rotateAngleX = Cheadud;
        this.CLEye.rotationPointZ = this.CHead1.rotationPointZ;
        this.CLEye.rotationPointX = this.CHead1.rotationPointX;
        this.CLEye.rotationPointY = this.CHead1.rotationPointY;
        this.CREye.rotateAngleX = Cheadud;
        this.CREye.rotationPointZ = this.CHead1.rotationPointZ;
        this.CREye.rotationPointX = this.CHead1.rotationPointX;
        this.CREye.rotationPointY = this.CHead1.rotationPointY;
        this.CLNoseSpike.rotateAngleX = 0.244f + Cheadud;
        this.CLNoseSpike.rotationPointZ = this.CHead1.rotationPointZ;
        this.CLNoseSpike.rotationPointX = this.CHead1.rotationPointX;
        this.CLNoseSpike.rotationPointY = this.CHead1.rotationPointY;
        this.CRNoseSpike.rotateAngleX = 0.261f + Cheadud;
        this.CRNoseSpike.rotationPointZ = this.CHead1.rotationPointZ;
        this.CRNoseSpike.rotationPointX = this.CHead1.rotationPointX;
        this.CRNoseSpike.rotationPointY = this.CHead1.rotationPointY;
        this.CJaw1.rotationPointY = this.CHead1.rotationPointY + (float)Math.cos(this.CHead1.rotateAngleX) * 14.0f;
        this.CJaw1.rotationPointZ = this.NeckC4.rotationPointZ + (this.CJaw1.rotationPointZ - this.NeckC4.rotationPointZ) * (float)Math.cos(this.NeckC4.rotateAngleX);
        this.CJaw1.rotationPointZ += (float)Math.sin(this.CHead1.rotateAngleX) * 14.0f;
        this.CJaw1.rotationPointX = this.NeckC4.rotationPointX + (this.CJaw1.rotationPointX - this.NeckC4.rotationPointX) * (float)Math.cos(this.NeckC4.rotateAngleX);
        this.CJaw2.rotationPointZ = this.CJaw1.rotationPointZ;
        this.CJaw2.rotationPointX = this.CJaw1.rotationPointX;
        this.CJaw2.rotationPointY = this.CJaw1.rotationPointY;
        this.CJaw3.rotationPointZ = this.CJaw1.rotationPointZ;
        this.CJaw3.rotationPointX = this.CJaw1.rotationPointX;
        this.CJaw3.rotationPointY = this.CJaw1.rotationPointY;
        this.CTooth1.rotationPointZ = this.CJaw1.rotationPointZ;
        this.CTooth1.rotationPointX = this.CJaw1.rotationPointX;
        this.CTooth1.rotationPointY = this.CJaw1.rotationPointY;
        this.CTooth2.rotationPointZ = this.CJaw1.rotationPointZ;
        this.CTooth2.rotationPointX = this.CJaw1.rotationPointX;
        this.CTooth2.rotationPointY = this.CJaw1.rotationPointY;
        this.CTooth3.rotationPointZ = this.CJaw1.rotationPointZ;
        this.CTooth3.rotationPointX = this.CJaw1.rotationPointX;
        this.CTooth3.rotationPointY = this.CJaw1.rotationPointY;
        this.CTooth4.rotationPointZ = this.CJaw1.rotationPointZ;
        this.CTooth4.rotationPointX = this.CJaw1.rotationPointX;
        this.CTooth4.rotationPointY = this.CJaw1.rotationPointY;
    }

    private void moveRightHead(float Rheadlr, float Rheadud, float Rjawangle) {
        this.RJaw1.rotateAngleX = Rjawangle;
        this.RJaw2.rotateAngleX = Rjawangle;
        this.RJaw3.rotateAngleX = Rjawangle;
        this.RTooth1.rotateAngleX = Rjawangle;
        this.RTooth2.rotateAngleX = Rjawangle;
        this.RTooth3.rotateAngleX = Rjawangle;
        this.RTooth4.rotateAngleX = Rjawangle;
        this.NeckR1.rotateAngleY = Rheadlr * 0.125f;
        this.NeckR2.rotationPointZ = this.NeckR1.rotationPointZ - (float)Math.cos(this.NeckR1.rotateAngleY) * 20.0f;
        this.NeckR2.rotationPointX = this.NeckR1.rotationPointX - (float)Math.sin(this.NeckR1.rotateAngleY) * 20.0f;
        this.NeckR2.rotateAngleY = Rheadlr * 0.25f;
        this.NeckR3.rotationPointZ = this.NeckR2.rotationPointZ - (float)Math.cos(this.NeckR2.rotateAngleY) * 36.0f;
        this.NeckR3.rotationPointX = this.NeckR2.rotationPointX - (float)Math.sin(this.NeckR2.rotateAngleY) * 36.0f;
        this.NeckR3.rotateAngleY = Rheadlr * 0.38f;
        this.NeckR4.rotationPointZ = this.NeckR3.rotationPointZ - (float)Math.cos(this.NeckR3.rotateAngleY) * 36.0f;
        this.NeckR4.rotationPointX = this.NeckR3.rotationPointX - (float)Math.sin(this.NeckR3.rotateAngleY) * 36.0f;
        this.NeckR4.rotateAngleY = Rheadlr * 0.5f;
        this.RHead1.rotationPointZ = this.NeckR4.rotationPointZ - (float)Math.cos(this.NeckR4.rotateAngleY) * 36.0f;
        this.RHead1.rotationPointX = this.NeckR4.rotationPointX - (float)Math.sin(this.NeckR4.rotateAngleY) * 36.0f;
        this.RHead1.rotateAngleY = Rheadlr;
        this.RHead2.rotateAngleY = Rheadlr;
        this.RHead2.rotationPointZ = this.RHead1.rotationPointZ;
        this.RHead2.rotationPointX = this.RHead1.rotationPointX;
        this.RHead3.rotateAngleY = Rheadlr;
        this.RHead3.rotationPointZ = this.RHead1.rotationPointZ;
        this.RHead3.rotationPointX = this.RHead1.rotationPointX;
        this.RHeadMane.rotateAngleY = Rheadlr;
        this.RHeadMane.rotationPointZ = this.RHead1.rotationPointZ;
        this.RHeadMane.rotationPointX = this.RHead1.rotationPointX;
        this.RLEye.rotateAngleY = Rheadlr;
        this.RLEye.rotationPointZ = this.RHead1.rotationPointZ;
        this.RLEye.rotationPointX = this.RHead1.rotationPointX;
        this.RREye.rotateAngleY = Rheadlr;
        this.RREye.rotationPointZ = this.RHead1.rotationPointZ;
        this.RREye.rotationPointX = this.RHead1.rotationPointX;
        this.RLNoseSpike.rotateAngleY = 0.244f + Rheadlr;
        this.RLNoseSpike.rotationPointZ = this.RHead1.rotationPointZ;
        this.RLNoseSpike.rotationPointX = this.RHead1.rotationPointX;
        this.RRNoseSpike.rotateAngleY = -0.261f + Rheadlr;
        this.RRNoseSpike.rotationPointZ = this.RHead1.rotationPointZ;
        this.RRNoseSpike.rotationPointX = this.RHead1.rotationPointX;
        this.RJaw1.rotateAngleY = Rheadlr;
        this.RJaw1.rotationPointZ = this.NeckR4.rotationPointZ - (float)Math.cos(this.NeckR4.rotateAngleY) * 37.0f;
        this.RJaw1.rotationPointX = this.NeckR4.rotationPointX - (float)Math.sin(this.NeckR4.rotateAngleY) * 37.0f;
        this.RJaw2.rotateAngleY = Rheadlr;
        this.RJaw2.rotationPointZ = this.RJaw1.rotationPointZ;
        this.RJaw2.rotationPointX = this.RJaw1.rotationPointX;
        this.RJaw3.rotateAngleY = Rheadlr;
        this.RJaw3.rotationPointZ = this.RJaw1.rotationPointZ;
        this.RJaw3.rotationPointX = this.RJaw1.rotationPointX;
        this.RTooth1.rotateAngleY = Rheadlr;
        this.RTooth1.rotationPointZ = this.RJaw1.rotationPointZ;
        this.RTooth1.rotationPointX = this.RJaw1.rotationPointX;
        this.RTooth2.rotateAngleY = Rheadlr;
        this.RTooth2.rotationPointZ = this.RJaw1.rotationPointZ;
        this.RTooth2.rotationPointX = this.RJaw1.rotationPointX;
        this.RTooth3.rotateAngleY = Rheadlr;
        this.RTooth3.rotationPointZ = this.RJaw1.rotationPointZ;
        this.RTooth3.rotationPointX = this.RJaw1.rotationPointX;
        this.RTooth4.rotateAngleY = Rheadlr;
        this.RTooth4.rotationPointZ = this.RJaw1.rotationPointZ;
        this.RTooth4.rotationPointX = this.RJaw1.rotationPointX;
        this.NeckR1.rotateAngleX = Rheadud * 0.125f;
        this.NeckR2.rotationPointY = this.NeckR1.rotationPointY + (float)Math.sin(this.NeckR1.rotateAngleX) * 20.0f;
        this.NeckR2.rotationPointZ = this.NeckR1.rotationPointZ + (this.NeckR2.rotationPointZ - this.NeckR1.rotationPointZ) * (float)Math.cos(this.NeckR1.rotateAngleX);
        this.NeckR2.rotationPointX = this.NeckR1.rotationPointX + (this.NeckR2.rotationPointX - this.NeckR1.rotationPointX) * (float)Math.cos(this.NeckR1.rotateAngleX);
        this.NeckR2.rotateAngleX = Rheadud * 0.25f;
        this.NeckR3.rotationPointY = this.NeckR2.rotationPointY + (float)Math.sin(this.NeckR2.rotateAngleX) * 36.0f;
        this.NeckR3.rotationPointZ = this.NeckR2.rotationPointZ + (this.NeckR3.rotationPointZ - this.NeckR2.rotationPointZ) * (float)Math.cos(this.NeckR2.rotateAngleX);
        this.NeckR3.rotationPointX = this.NeckR2.rotationPointX + (this.NeckR3.rotationPointX - this.NeckR2.rotationPointX) * (float)Math.cos(this.NeckR2.rotateAngleX);
        this.NeckR3.rotateAngleX = Rheadud * 0.38f;
        this.NeckR4.rotationPointY = this.NeckR3.rotationPointY + (float)Math.sin(this.NeckR3.rotateAngleX) * 36.0f;
        this.NeckR4.rotationPointZ = this.NeckR3.rotationPointZ + (this.NeckR4.rotationPointZ - this.NeckR3.rotationPointZ) * (float)Math.cos(this.NeckR3.rotateAngleX);
        this.NeckR4.rotationPointX = this.NeckR3.rotationPointX + (this.NeckR4.rotationPointX - this.NeckR3.rotationPointX) * (float)Math.cos(this.NeckR3.rotateAngleX);
        this.NeckR4.rotateAngleX = Rheadud * 0.5f;
        this.RHead1.rotationPointY = this.NeckR4.rotationPointY + (float)Math.sin(this.NeckR4.rotateAngleX) * 36.0f;
        this.RHead1.rotationPointZ = this.NeckR4.rotationPointZ + (this.RHead1.rotationPointZ - this.NeckR4.rotationPointZ) * (float)Math.cos(this.NeckR4.rotateAngleX);
        this.RHead1.rotationPointX = this.NeckR4.rotationPointX + (this.RHead1.rotationPointX - this.NeckR4.rotationPointX) * (float)Math.cos(this.NeckR4.rotateAngleX);
        this.RHead1.rotateAngleX = Rheadud;
        this.RHead2.rotateAngleX = Rheadud;
        this.RHead2.rotationPointZ = this.RHead1.rotationPointZ;
        this.RHead2.rotationPointX = this.RHead1.rotationPointX;
        this.RHead2.rotationPointY = this.RHead1.rotationPointY;
        this.RHead3.rotateAngleX = Rheadud;
        this.RHead3.rotationPointZ = this.RHead1.rotationPointZ;
        this.RHead3.rotationPointX = this.RHead1.rotationPointX;
        this.RHead3.rotationPointY = this.RHead1.rotationPointY;
        this.RHeadMane.rotateAngleX = 0.384f + Rheadud;
        this.RHeadMane.rotationPointZ = this.RHead1.rotationPointZ;
        this.RHeadMane.rotationPointX = this.RHead1.rotationPointX;
        this.RHeadMane.rotationPointY = this.RHead1.rotationPointY;
        this.RLEye.rotateAngleX = Rheadud;
        this.RLEye.rotationPointZ = this.RHead1.rotationPointZ;
        this.RLEye.rotationPointX = this.RHead1.rotationPointX;
        this.RLEye.rotationPointY = this.RHead1.rotationPointY;
        this.RREye.rotateAngleX = Rheadud;
        this.RREye.rotationPointZ = this.RHead1.rotationPointZ;
        this.RREye.rotationPointX = this.RHead1.rotationPointX;
        this.RREye.rotationPointY = this.RHead1.rotationPointY;
        this.RLNoseSpike.rotateAngleX = 0.244f + Rheadud;
        this.RLNoseSpike.rotationPointZ = this.RHead1.rotationPointZ;
        this.RLNoseSpike.rotationPointX = this.RHead1.rotationPointX;
        this.RLNoseSpike.rotationPointY = this.RHead1.rotationPointY;
        this.RRNoseSpike.rotateAngleX = 0.261f + Rheadud;
        this.RRNoseSpike.rotationPointZ = this.RHead1.rotationPointZ;
        this.RRNoseSpike.rotationPointX = this.RHead1.rotationPointX;
        this.RRNoseSpike.rotationPointY = this.RHead1.rotationPointY;
        this.RJaw1.rotationPointY = this.RHead1.rotationPointY + (float)Math.cos(this.RHead1.rotateAngleX) * 14.0f;
        this.RJaw1.rotationPointZ = this.NeckR4.rotationPointZ + (this.RJaw1.rotationPointZ - this.NeckR4.rotationPointZ) * (float)Math.cos(this.NeckR4.rotateAngleX);
        this.RJaw1.rotationPointZ += (float)Math.sin(this.RHead1.rotateAngleX) * 14.0f;
        this.RJaw1.rotationPointX = this.NeckR4.rotationPointX + (this.RJaw1.rotationPointX - this.NeckR4.rotationPointX) * (float)Math.cos(this.NeckR4.rotateAngleX);
        this.RJaw2.rotationPointZ = this.RJaw1.rotationPointZ;
        this.RJaw2.rotationPointX = this.RJaw1.rotationPointX;
        this.RJaw2.rotationPointY = this.RJaw1.rotationPointY;
        this.RJaw3.rotationPointZ = this.RJaw1.rotationPointZ;
        this.RJaw3.rotationPointX = this.RJaw1.rotationPointX;
        this.RJaw3.rotationPointY = this.RJaw1.rotationPointY;
        this.RTooth1.rotationPointZ = this.RJaw1.rotationPointZ;
        this.RTooth1.rotationPointX = this.RJaw1.rotationPointX;
        this.RTooth1.rotationPointY = this.RJaw1.rotationPointY;
        this.RTooth2.rotationPointZ = this.RJaw1.rotationPointZ;
        this.RTooth2.rotationPointX = this.RJaw1.rotationPointX;
        this.RTooth2.rotationPointY = this.RJaw1.rotationPointY;
        this.RTooth3.rotationPointZ = this.RJaw1.rotationPointZ;
        this.RTooth3.rotationPointX = this.RJaw1.rotationPointX;
        this.RTooth3.rotationPointY = this.RJaw1.rotationPointY;
        this.RTooth4.rotationPointZ = this.RJaw1.rotationPointZ;
        this.RTooth4.rotationPointX = this.RJaw1.rotationPointX;
        this.RTooth4.rotationPointY = this.RJaw1.rotationPointY;
    }
}

